# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in proto.gemspec
gemspec

gem 'grpc', "~> 1.50.0"
gem 'grpc-tools', "~> 1.50.0"
gem 'google-protobuf', "~> 3.21.12"
gem "rake", "~> 13.0"
