# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in proto.gemspec
gemspec

gem 'google-protobuf', '~> 3.23.4'
gem 'grpc', '~> 1.56.2'
gem 'grpc-tools', '~> 1.56.2'
gem 'rake', '~> 13.0'
