<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/block.proto

namespace Schema\V2\Block;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v2.Block.Content</code>
 */
class Content extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string value = 2;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>optional string href = 3;</code>
     */
    protected $href = null;
    /**
     * Generated from protobuf field <code>.schema.v2.Block.Style styles = 4;</code>
     */
    protected $styles = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type string $value
     *     @type string $href
     *     @type \Schema\V2\Block\Style $styles
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string href = 3;</code>
     * @return string
     */
    public function getHref()
    {
        return isset($this->href) ? $this->href : '';
    }

    public function hasHref()
    {
        return isset($this->href);
    }

    public function clearHref()
    {
        unset($this->href);
    }

    /**
     * Generated from protobuf field <code>optional string href = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHref($var)
    {
        GPBUtil::checkString($var, True);
        $this->href = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v2.Block.Style styles = 4;</code>
     * @return \Schema\V2\Block\Style|null
     */
    public function getStyles()
    {
        return $this->styles;
    }

    public function hasStyles()
    {
        return isset($this->styles);
    }

    public function clearStyles()
    {
        unset($this->styles);
    }

    /**
     * Generated from protobuf field <code>.schema.v2.Block.Style styles = 4;</code>
     * @param \Schema\V2\Block\Style $var
     * @return $this
     */
    public function setStyles($var)
    {
        GPBUtil::checkMessage($var, \Schema\V2\Block\Style::class);
        $this->styles = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Content::class, \Schema\V2\Block_Content::class);

