<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1\Table\ColumnValidationOption;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.Table.ColumnValidationOption.DateValidation</code>
 */
class DateValidation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool past = 1;</code>
     */
    protected $past = false;
    /**
     * Generated from protobuf field <code>bool future = 2;</code>
     */
    protected $future = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $past
     *     @type bool $future
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool past = 1;</code>
     * @return bool
     */
    public function getPast()
    {
        return $this->past;
    }

    /**
     * Generated from protobuf field <code>bool past = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setPast($var)
    {
        GPBUtil::checkBool($var);
        $this->past = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool future = 2;</code>
     * @return bool
     */
    public function getFuture()
    {
        return $this->future;
    }

    /**
     * Generated from protobuf field <code>bool future = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setFuture($var)
    {
        GPBUtil::checkBool($var);
        $this->future = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DateValidation::class, \Schema\V1\Table_ColumnValidationOption_DateValidation::class);

