<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1\Localization;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.Localization.Namespace</code>
 */
class PBNamespace extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .schema.v1.Localization.Translate translates = 2;</code>
     */
    private $translates;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type array<\Schema\V1\Localization\Translate>|\Google\Protobuf\Internal\RepeatedField $translates
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Localization.Translate translates = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTranslates()
    {
        return $this->translates;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Localization.Translate translates = 2;</code>
     * @param array<\Schema\V1\Localization\Translate>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTranslates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\Localization\Translate::class);
        $this->translates = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PBNamespace::class, \Schema\V1\Localization_Namespace::class);

