<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Schema\V1\Table;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.Table.ColumnValidation</code>
 */
class ColumnValidation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.ColumnValidationOption column_validation_options = 1;</code>
     */
    private $column_validation_options;
    /**
     * Generated from protobuf field <code>bool presence = 2;</code>
     */
    protected $presence = false;
    /**
     * Generated from protobuf field <code>bool uniqueness = 3;</code>
     */
    protected $uniqueness = false;
    /**
     * Generated from protobuf field <code>bool allow_nil = 4;</code>
     */
    protected $allow_nil = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Schema\V1\Table\ColumnValidationOption>|\Google\Protobuf\Internal\RepeatedField $column_validation_options
     *     @type bool $presence
     *     @type bool $uniqueness
     *     @type bool $allow_nil
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.ColumnValidationOption column_validation_options = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumnValidationOptions()
    {
        return $this->column_validation_options;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.ColumnValidationOption column_validation_options = 1;</code>
     * @param array<\Schema\V1\Table\ColumnValidationOption>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumnValidationOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\Table\ColumnValidationOption::class);
        $this->column_validation_options = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool presence = 2;</code>
     * @return bool
     */
    public function getPresence()
    {
        return $this->presence;
    }

    /**
     * Generated from protobuf field <code>bool presence = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setPresence($var)
    {
        GPBUtil::checkBool($var);
        $this->presence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool uniqueness = 3;</code>
     * @return bool
     */
    public function getUniqueness()
    {
        return $this->uniqueness;
    }

    /**
     * Generated from protobuf field <code>bool uniqueness = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setUniqueness($var)
    {
        GPBUtil::checkBool($var);
        $this->uniqueness = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool allow_nil = 4;</code>
     * @return bool
     */
    public function getAllowNil()
    {
        return $this->allow_nil;
    }

    /**
     * Generated from protobuf field <code>bool allow_nil = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowNil($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_nil = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ColumnValidation::class, \Schema\V1\Table_ColumnValidation::class);

