# frozen_string_literal: true

require_relative 'payloads/v1/payloads_pb'
require_relative 'payloads/v1/payloads_services_pb'
require_relative 'payloads/v1/project_export_pb'
require_relative 'payloads/v1/project_import_pb'
require_relative 'payloads/v2/block_core_pb'
require_relative 'payloads/v2/component_specification_pb'
require_relative 'payloads/v2/project_source_pb'
require_relative 'payloads/v2/specification_pb'
require_relative 'payloads/v2/project_generate_queue_pb'
require_relative 'payloads/v2/use_case_creation_pb'
require_relative 'payloads/v2/business_logic_pb'
require_relative 'payloads/v2/block_pb'
require_relative 'payloads/v2/project_figma_pb'
require_relative 'payloads/v2/project_preview_pb'
require_relative 'payloads/v2/project_git_pb'
require_relative 'payloads/v2/translation_blocks_pb'
require_relative 'payloads/v2/project_source_frontend_pb'
require_relative 'payloads/v2/project_ticket_pb'
require_relative 'payloads/v2/image_description_pb'
require_relative 'payloads/v2/ai_usage_report_pb'
require_relative 'payloads/v2/index_block_document_pb'
require_relative 'payloads/v2/test_case_pb'
require_relative 'payloads/v2/ai_review_pb'
require_relative 'payloads/v2/project_pdf_pb'
require_relative 'payloads/v2/chat_pb'
require_relative 'payloads/v2/inline_prompt_pb'

module JiteraProto
end
