<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2\ProjectSourceInit;

use UnexpectedValueException;

/**
 * Protobuf type <code>schema.v2.ProjectSourceInit.Layer</code>
 */
class Layer
{
    /**
     * Generated from protobuf enum <code>LAYER_UNSPECIFIED = 0;</code>
     */
    const LAYER_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>BACKEND = 1;</code>
     */
    const BACKEND = 1;
    /**
     * Generated from protobuf enum <code>FRONTEND = 2;</code>
     */
    const FRONTEND = 2;
    /**
     * Generated from protobuf enum <code>MOBILE = 3;</code>
     */
    const MOBILE = 3;

    private static $valueToName = [
        self::LAYER_UNSPECIFIED => 'LAYER_UNSPECIFIED',
        self::BACKEND => 'BACKEND',
        self::FRONTEND => 'FRONTEND',
        self::MOBILE => 'MOBILE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Layer::class, \Schema\V2\ProjectSourceInit_Layer::class);

