<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2\ProjectSourceReport;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v2.ProjectSourceReport.Complete</code>
 */
class Complete extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string files = 4;</code>
     */
    protected $files = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $files
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\ProjectSource::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string files = 4;</code>
     * @return string
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * Generated from protobuf field <code>string files = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFiles($var)
    {
        GPBUtil::checkString($var, True);
        $this->files = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Complete::class, \Schema\V2\ProjectSourceReport_Complete::class);

