<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2\ProjectSourceReport;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v2.ProjectSourceReport.Progress</code>
 */
class Progress extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 precentage = 1;</code>
     */
    protected $precentage = 0;
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $precentage
     *     @type string $message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\ProjectSource::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 precentage = 1;</code>
     * @return int
     */
    public function getPrecentage()
    {
        return $this->precentage;
    }

    /**
     * Generated from protobuf field <code>int32 precentage = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPrecentage($var)
    {
        GPBUtil::checkInt32($var);
        $this->precentage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Progress::class, \Schema\V2\ProjectSourceReport_Progress::class);

