<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1\Feature;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.Feature.EmailConfig</code>
 */
class EmailConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>string username = 2;</code>
     */
    protected $username = '';
    /**
     * Generated from protobuf field <code>string password = 3;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string default_from_email = 4;</code>
     */
    protected $default_from_email = '';
    /**
     * Generated from protobuf field <code>.schema.v1.Feature.EmailServiceProvider service_provider = 5;</code>
     */
    protected $service_provider = 0;
    /**
     * Generated from protobuf field <code>string port = 6;</code>
     */
    protected $port = '';
    /**
     * Generated from protobuf field <code>.schema.v1.Feature.EmailConfigAuthentication authentication = 7;</code>
     */
    protected $authentication = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type string $username
     *     @type string $password
     *     @type string $default_from_email
     *     @type int $service_provider
     *     @type string $port
     *     @type int $authentication
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string default_from_email = 4;</code>
     * @return string
     */
    public function getDefaultFromEmail()
    {
        return $this->default_from_email;
    }

    /**
     * Generated from protobuf field <code>string default_from_email = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDefaultFromEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->default_from_email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Feature.EmailServiceProvider service_provider = 5;</code>
     * @return int
     */
    public function getServiceProvider()
    {
        return $this->service_provider;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Feature.EmailServiceProvider service_provider = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setServiceProvider($var)
    {
        GPBUtil::checkEnum($var, \Schema\V1\Feature\EmailServiceProvider::class);
        $this->service_provider = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string port = 6;</code>
     * @return string
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>string port = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkString($var, True);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Feature.EmailConfigAuthentication authentication = 7;</code>
     * @return int
     */
    public function getAuthentication()
    {
        return $this->authentication;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Feature.EmailConfigAuthentication authentication = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAuthentication($var)
    {
        GPBUtil::checkEnum($var, \Schema\V1\Feature\EmailConfigAuthentication::class);
        $this->authentication = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(EmailConfig::class, \Schema\V1\Feature_EmailConfig::class);

