<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Schema\V1\Feature;

use UnexpectedValueException;

/**
 * Protobuf type <code>schema.v1.Feature.FeatureName</code>
 */
class FeatureName
{
    /**
     * Generated from protobuf enum <code>NIL = 0;</code>
     */
    const NIL = 0;
    /**
     * Generated from protobuf enum <code>EMAIL_LOGIN = 1;</code>
     */
    const EMAIL_LOGIN = 1;
    /**
     * Generated from protobuf enum <code>JP_BANKS_DATA = 2;</code>
     */
    const JP_BANKS_DATA = 2;
    /**
     * Generated from protobuf enum <code>BASIC_AUTH = 3;</code>
     */
    const BASIC_AUTH = 3;
    /**
     * Generated from protobuf enum <code>TWILIO_LOGIN = 4;</code>
     */
    const TWILIO_LOGIN = 4;
    /**
     * Generated from protobuf enum <code>ROLLBAR = 5;</code>
     */
    const ROLLBAR = 5;
    /**
     * Generated from protobuf enum <code>DEEP_LINK = 6;</code>
     */
    const DEEP_LINK = 6;
    /**
     * Generated from protobuf enum <code>STRIPE = 7;</code>
     */
    const STRIPE = 7;
    /**
     * Generated from protobuf enum <code>LINE_LOGIN = 8;</code>
     */
    const LINE_LOGIN = 8;
    /**
     * Generated from protobuf enum <code>GOOGLE_ANALYTICS = 9;</code>
     */
    const GOOGLE_ANALYTICS = 9;
    /**
     * Generated from protobuf enum <code>SCOUT_APM = 10;</code>
     */
    const SCOUT_APM = 10;
    /**
     * Generated from protobuf enum <code>GOOGLE_TAG_MANAGER = 11;</code>
     */
    const GOOGLE_TAG_MANAGER = 11;
    /**
     * Generated from protobuf enum <code>EMAIL_CONFIG = 12;</code>
     */
    const EMAIL_CONFIG = 12;

    private static $valueToName = [
        self::NIL => 'NIL',
        self::EMAIL_LOGIN => 'EMAIL_LOGIN',
        self::JP_BANKS_DATA => 'JP_BANKS_DATA',
        self::BASIC_AUTH => 'BASIC_AUTH',
        self::TWILIO_LOGIN => 'TWILIO_LOGIN',
        self::ROLLBAR => 'ROLLBAR',
        self::DEEP_LINK => 'DEEP_LINK',
        self::STRIPE => 'STRIPE',
        self::LINE_LOGIN => 'LINE_LOGIN',
        self::GOOGLE_ANALYTICS => 'GOOGLE_ANALYTICS',
        self::SCOUT_APM => 'SCOUT_APM',
        self::GOOGLE_TAG_MANAGER => 'GOOGLE_TAG_MANAGER',
        self::EMAIL_CONFIG => 'EMAIL_CONFIG',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(FeatureName::class, \Schema\V1\Feature_FeatureName::class);

