<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2\ApiChanges;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v2.ApiChanges.ApiSchema</code>
 */
class ApiSchema extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int32 usecaseId = 2;</code>
     */
    protected $usecaseId = 0;
    /**
     * Generated from protobuf field <code>string content = 3;</code>
     */
    protected $content = '';
    /**
     * Generated from protobuf field <code>bool authenticated = 4;</code>
     */
    protected $authenticated = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $usecaseId
     *     @type string $content
     *     @type bool $authenticated
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\ProjectSource::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 usecaseId = 2;</code>
     * @return int
     */
    public function getUsecaseId()
    {
        return $this->usecaseId;
    }

    /**
     * Generated from protobuf field <code>int32 usecaseId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUsecaseId($var)
    {
        GPBUtil::checkInt32($var);
        $this->usecaseId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool authenticated = 4;</code>
     * @return bool
     */
    public function getAuthenticated()
    {
        return $this->authenticated;
    }

    /**
     * Generated from protobuf field <code>bool authenticated = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setAuthenticated($var)
    {
        GPBUtil::checkBool($var);
        $this->authenticated = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ApiSchema::class, \Schema\V2\ApiChanges_ApiSchema::class);

