<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/user_case_creation.proto

namespace Schema\V2\UserCaseCreationResponse;

use UnexpectedValueException;

/**
 * Protobuf type <code>schema.v2.UserCaseCreationResponse.Module</code>
 */
class Module
{
    /**
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>BUSINESS_LOGIC = 1;</code>
     */
    const BUSINESS_LOGIC = 1;
    /**
     * Generated from protobuf enum <code>ERD = 2;</code>
     */
    const ERD = 2;
    /**
     * Generated from protobuf enum <code>API = 3;</code>
     */
    const API = 3;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::BUSINESS_LOGIC => 'BUSINESS_LOGIC',
        self::ERD => 'ERD',
        self::API => 'API',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Module::class, \Schema\V2\UserCaseCreationResponse_Module::class);

