<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1\Table\Column;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.Table.Column.BooleanType</code>
 */
class BooleanType extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool default_value = 1;</code>
     */
    protected $default_value = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $default_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool default_value = 1;</code>
     * @return bool
     */
    public function getDefaultValue()
    {
        return $this->default_value;
    }

    /**
     * Generated from protobuf field <code>bool default_value = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setDefaultValue($var)
    {
        GPBUtil::checkBool($var);
        $this->default_value = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(BooleanType::class, \Schema\V1\Table_Column_BooleanType::class);

