<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1\Table\Column;

use UnexpectedValueException;

/**
 * Protobuf type <code>schema.v1.Table.Column.Operator</code>
 */
class Operator
{
    /**
     * Generated from protobuf enum <code>GREATER_THAN = 0;</code>
     */
    const GREATER_THAN = 0;
    /**
     * Generated from protobuf enum <code>GREATER_THAN_OR_EQUAL = 1;</code>
     */
    const GREATER_THAN_OR_EQUAL = 1;
    /**
     * Generated from protobuf enum <code>EQUAL = 2;</code>
     */
    const EQUAL = 2;
    /**
     * Generated from protobuf enum <code>LESS_THAN = 3;</code>
     */
    const LESS_THAN = 3;
    /**
     * Generated from protobuf enum <code>LESS_THAN_OR_EQUAL = 4;</code>
     */
    const LESS_THAN_OR_EQUAL = 4;
    /**
     * Generated from protobuf enum <code>NOT_EQUAL = 5;</code>
     */
    const NOT_EQUAL = 5;

    private static $valueToName = [
        self::GREATER_THAN => 'GREATER_THAN',
        self::GREATER_THAN_OR_EQUAL => 'GREATER_THAN_OR_EQUAL',
        self::EQUAL => 'EQUAL',
        self::LESS_THAN => 'LESS_THAN',
        self::LESS_THAN_OR_EQUAL => 'LESS_THAN_OR_EQUAL',
        self::NOT_EQUAL => 'NOT_EQUAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Operator::class, \Schema\V1\Table_Column_Operator::class);

