<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1\Controller\ResourceCondition;

use UnexpectedValueException;

/**
 * Protobuf type <code>schema.v1.Controller.ResourceCondition.System</code>
 */
class System
{
    /**
     * Generated from protobuf enum <code>RESOURCE_OWNER = 0;</code>
     */
    const RESOURCE_OWNER = 0;

    private static $valueToName = [
        self::RESOURCE_OWNER => 'RESOURCE_OWNER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(System::class, \Schema\V1\Controller_ResourceCondition_System::class);

