<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1\FormValidation;

use UnexpectedValueException;

/**
 * Protobuf type <code>schema.v1.FormValidation.RuleType</code>
 */
class RuleType
{
    /**
     * Generated from protobuf enum <code>REQUIRED = 0;</code>
     */
    const REQUIRED = 0;
    /**
     * Generated from protobuf enum <code>MAXIMUM = 1;</code>
     */
    const MAXIMUM = 1;
    /**
     * Generated from protobuf enum <code>MINIMUM = 2;</code>
     */
    const MINIMUM = 2;
    /**
     * Generated from protobuf enum <code>REGEX = 3;</code>
     */
    const REGEX = 3;

    private static $valueToName = [
        self::REQUIRED => 'REQUIRED',
        self::MAXIMUM => 'MAXIMUM',
        self::MINIMUM => 'MINIMUM',
        self::REGEX => 'REGEX',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(RuleType::class, \Schema\V1\FormValidation_RuleType::class);

