# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/project_export.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("v1/project_export.proto", :syntax => :proto3) do
    add_message "schema.v1.Report" do
      optional :project_name, :string, 1
      optional :project_id, :int32, 2
      oneof :state do
        optional :progress, :message, 3, "schema.v1.Report.Progress"
        optional :complete, :message, 4, "schema.v1.Report.Complete"
        optional :error, :message, 5, "schema.v1.Report.Error"
      end
      oneof :report_type do
        optional :project_export, :message, 6, "schema.v1.Report.ProjectExport"
        optional :project_preview, :message, 7, "schema.v1.Report.ProjectPreview"
      end
    end
    add_message "schema.v1.Report.Progress" do
      optional :percentage, :float, 1
      optional :message, :string, 2
    end
    add_message "schema.v1.Report.Complete" do
      optional :path, :string, 1
    end
    add_message "schema.v1.Report.ProjectExport" do
      optional :id, :int32, 1
    end
    add_message "schema.v1.Report.ProjectPreview" do
      optional :id, :int32, 1
    end
    add_message "schema.v1.Report.Error" do
      optional :message, :string, 1
    end
  end
end

module Schema
  module V1
    Report = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.Report").msgclass
    Report::Progress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.Report.Progress").msgclass
    Report::Complete = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.Report.Complete").msgclass
    Report::ProjectExport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.Report.ProjectExport").msgclass
    Report::ProjectPreview = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.Report.ProjectPreview").msgclass
    Report::Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.Report.Error").msgclass
  end
end
