# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/project_import.proto

require 'google/protobuf'


descriptor_data = "\n\x17v1/project_import.proto\x12\tschema.v1\"\x8b\x02\n\x0fProjectAnalysis\x12\x19\n\x11project_import_id\x18\x01 \x01(\x05\x12\x0c\n\x04repo\x18\x02 \x01(\t\x12\r\n\x05owner\x18\x03 \x01(\t\x12\x0e\n\x06\x62ranch\x18\x04 \x01(\t\x12\r\n\x05token\x18\x05 \x01(\t\x12:\n\x08provider\x18\x06 \x01(\x0e\x32#.schema.v1.ProjectAnalysis.ProviderH\x00\x88\x01\x01\x12\x1e\n\x11provider_host_url\x18\x07 \x01(\tH\x01\x88\x01\x01\"\"\n\x08Provider\x12\n\n\x06github\x10\x00\x12\n\n\x06gitlab\x10\x01\x42\x0b\n\t_providerB\x14\n\x12_provider_host_url\"\xe2\x02\n\x15ProjectAnalysisReport\x12\x19\n\x11project_import_id\x18\x01 \x01(\x05\x12=\n\x08progress\x18\x02 \x01(\x0b\x32).schema.v1.ProjectAnalysisReport.ProgressH\x00\x12\x37\n\x05\x65rror\x18\x03 \x01(\x0b\x32&.schema.v1.ProjectAnalysisReport.ErrorH\x00\x1aj\n\x08Progress\x12\x12\n\npercentage\x18\x01 \x01(\x02\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x39\n\x07payload\x18\x03 \x01(\x0b\x32(.schema.v1.ProjectAnalysisReport.Payload\x1a\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\x1a\'\n\x07Payload\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0e\n\x06module\x18\x02 \x01(\tB\x07\n\x05stateb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Schema
  module V1
    ProjectAnalysis = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ProjectAnalysis").msgclass
    ProjectAnalysis::Provider = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ProjectAnalysis.Provider").enummodule
    ProjectAnalysisReport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ProjectAnalysisReport").msgclass
    ProjectAnalysisReport::Progress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ProjectAnalysisReport.Progress").msgclass
    ProjectAnalysisReport::Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ProjectAnalysisReport.Error").msgclass
    ProjectAnalysisReport::Payload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v1.ProjectAnalysisReport.Payload").msgclass
  end
end
