<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_figma.proto

namespace Schema\V2\ProjectFigmaImportResponse;

use UnexpectedValueException;

/**
 * Protobuf type <code>schema.v2.ProjectFigmaImportResponse.Module</code>
 */
class Module
{
    /**
     * Generated from protobuf enum <code>FIGMA_TO_NATURAL_LANGUAGE = 0;</code>
     */
    const FIGMA_TO_NATURAL_LANGUAGE = 0;

    private static $valueToName = [
        self::FIGMA_TO_NATURAL_LANGUAGE => 'FIGMA_TO_NATURAL_LANGUAGE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Module::class, \Schema\V2\ProjectFigmaImportResponse_Module::class);

