<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_figma.proto

namespace Schema\V2\ProjectFigmaImportResponse;

use UnexpectedValueException;

/**
 * Protobuf type <code>schema.v2.ProjectFigmaImportResponse.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>SUCCEEDED = 0;</code>
     */
    const SUCCEEDED = 0;
    /**
     * Generated from protobuf enum <code>INPROGRESS = 1;</code>
     */
    const INPROGRESS = 1;
    /**
     * Generated from protobuf enum <code>FAILED = 2;</code>
     */
    const FAILED = 2;

    private static $valueToName = [
        self::SUCCEEDED => 'SUCCEEDED',
        self::INPROGRESS => 'INPROGRESS',
        self::FAILED => 'FAILED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \Schema\V2\ProjectFigmaImportResponse_Status::class);

