<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\ApiChanges\Column instead.
     * @deprecated
     */
    class ApiChanges_Column {}
}
class_exists(ApiChanges\Column::class);
@trigger_error('Schema\V2\ApiChanges_Column is deprecated and will be removed in the next major release. Use Schema\V2\ApiChanges\Column instead', E_USER_DEPRECATED);

