<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\ApiChanges\ApiSchema instead.
     * @deprecated
     */
    class ApiChanges_ApiSchema {}
}
class_exists(ApiChanges\ApiSchema::class);
@trigger_error('Schema\V2\ApiChanges_ApiSchema is deprecated and will be removed in the next major release. Use Schema\V2\ApiChanges\ApiSchema instead', E_USER_DEPRECATED);

