<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\BlockDiff\Block\Deletion instead.
     * @deprecated
     */
    class BlockDiff_Block_Deletion {}
}
class_exists(BlockDiff\Block\Deletion::class);
@trigger_error('Schema\V2\BlockDiff_Block_Deletion is deprecated and will be removed in the next major release. Use Schema\V2\BlockDiff\Block\Deletion instead', E_USER_DEPRECATED);

