<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\BlockChanges\BlockBody instead.
     * @deprecated
     */
    class BlockChanges_BlockBody {}
}
class_exists(BlockChanges\BlockBody::class);
@trigger_error('Schema\V2\BlockChanges_BlockBody is deprecated and will be removed in the next major release. Use Schema\V2\BlockChanges\BlockBody instead', E_USER_DEPRECATED);

