<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/block.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\Block\ExternalUrl instead.
     * @deprecated
     */
    class Block_ExternalUrl {}
}
class_exists(Block\ExternalUrl::class);
@trigger_error('Schema\V2\Block_ExternalUrl is deprecated and will be removed in the next major release. Use Schema\V2\Block\ExternalUrl instead', E_USER_DEPRECATED);

