<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\BlockDiff\Block\Addition instead.
     * @deprecated
     */
    class BlockDiff_Block_Addition {}
}
class_exists(BlockDiff\Block\Addition::class);
@trigger_error('Schema\V2\BlockDiff_Block_Addition is deprecated and will be removed in the next major release. Use Schema\V2\BlockDiff\Block\Addition instead', E_USER_DEPRECATED);

