<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\BusinessLogicChanges\Relation instead.
     * @deprecated
     */
    class BusinessLogicChanges_Relation {}
}
class_exists(BusinessLogicChanges\Relation::class);
@trigger_error('Schema\V2\BusinessLogicChanges_Relation is deprecated and will be removed in the next major release. Use Schema\V2\BusinessLogicChanges\Relation instead', E_USER_DEPRECATED);

