<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/business_logic.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\BusinessLogic\Property instead.
     * @deprecated
     */
    class BusinessLogic_Property {}
}
class_exists(BusinessLogic\Property::class);
@trigger_error('Schema\V2\BusinessLogic_Property is deprecated and will be removed in the next major release. Use Schema\V2\BusinessLogic\Property instead', E_USER_DEPRECATED);

