<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v2.BusinessLogicChanges</code>
 */
class BusinessLogicChanges extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 1;</code>
     */
    protected $project_generate_queue_id = 0;
    /**
     * Generated from protobuf field <code>repeated .schema.v2.ProjectSource.Table tables = 2;</code>
     */
    private $tables;
    /**
     * Generated from protobuf field <code>repeated .schema.v2.ProjectSource.Relation relations = 3;</code>
     */
    private $relations;
    /**
     * Generated from protobuf field <code>.schema.v2.ProjectSource project_source = 4;</code>
     */
    protected $project_source = null;
    /**
     * Generated from protobuf field <code>.schema.v2.BlockDiff block_diff = 5;</code>
     */
    protected $block_diff = null;
    /**
     * Generated from protobuf field <code>.schema.v2.Git git = 6;</code>
     */
    protected $git = null;
    /**
     * Generated from protobuf field <code>optional .schema.v2.ImportBy import_by = 7;</code>
     */
    protected $import_by = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $project_generate_queue_id
     *     @type array<\Schema\V2\ProjectSource\Table>|\Google\Protobuf\Internal\RepeatedField $tables
     *     @type array<\Schema\V2\ProjectSource\Relation>|\Google\Protobuf\Internal\RepeatedField $relations
     *     @type \Schema\V2\ProjectSource $project_source
     *     @type \Schema\V2\BlockDiff $block_diff
     *     @type \Schema\V2\Git $git
     *     @type int $import_by
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\ProjectSource::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 1;</code>
     * @return int
     */
    public function getProjectGenerateQueueId()
    {
        return $this->project_generate_queue_id;
    }

    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProjectGenerateQueueId($var)
    {
        GPBUtil::checkInt32($var);
        $this->project_generate_queue_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.ProjectSource.Table tables = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTables()
    {
        return $this->tables;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.ProjectSource.Table tables = 2;</code>
     * @param array<\Schema\V2\ProjectSource\Table>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTables($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V2\ProjectSource\Table::class);
        $this->tables = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.ProjectSource.Relation relations = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRelations()
    {
        return $this->relations;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.ProjectSource.Relation relations = 3;</code>
     * @param array<\Schema\V2\ProjectSource\Relation>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRelations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V2\ProjectSource\Relation::class);
        $this->relations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v2.ProjectSource project_source = 4;</code>
     * @return \Schema\V2\ProjectSource|null
     */
    public function getProjectSource()
    {
        return $this->project_source;
    }

    public function hasProjectSource()
    {
        return isset($this->project_source);
    }

    public function clearProjectSource()
    {
        unset($this->project_source);
    }

    /**
     * Generated from protobuf field <code>.schema.v2.ProjectSource project_source = 4;</code>
     * @param \Schema\V2\ProjectSource $var
     * @return $this
     */
    public function setProjectSource($var)
    {
        GPBUtil::checkMessage($var, \Schema\V2\ProjectSource::class);
        $this->project_source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v2.BlockDiff block_diff = 5;</code>
     * @return \Schema\V2\BlockDiff|null
     */
    public function getBlockDiff()
    {
        return $this->block_diff;
    }

    public function hasBlockDiff()
    {
        return isset($this->block_diff);
    }

    public function clearBlockDiff()
    {
        unset($this->block_diff);
    }

    /**
     * Generated from protobuf field <code>.schema.v2.BlockDiff block_diff = 5;</code>
     * @param \Schema\V2\BlockDiff $var
     * @return $this
     */
    public function setBlockDiff($var)
    {
        GPBUtil::checkMessage($var, \Schema\V2\BlockDiff::class);
        $this->block_diff = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v2.Git git = 6;</code>
     * @return \Schema\V2\Git|null
     */
    public function getGit()
    {
        return $this->git;
    }

    public function hasGit()
    {
        return isset($this->git);
    }

    public function clearGit()
    {
        unset($this->git);
    }

    /**
     * Generated from protobuf field <code>.schema.v2.Git git = 6;</code>
     * @param \Schema\V2\Git $var
     * @return $this
     */
    public function setGit($var)
    {
        GPBUtil::checkMessage($var, \Schema\V2\Git::class);
        $this->git = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .schema.v2.ImportBy import_by = 7;</code>
     * @return int
     */
    public function getImportBy()
    {
        return isset($this->import_by) ? $this->import_by : 0;
    }

    public function hasImportBy()
    {
        return isset($this->import_by);
    }

    public function clearImportBy()
    {
        unset($this->import_by);
    }

    /**
     * Generated from protobuf field <code>optional .schema.v2.ImportBy import_by = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setImportBy($var)
    {
        GPBUtil::checkEnum($var, \Schema\V2\ImportBy::class);
        $this->import_by = $var;

        return $this;
    }

}

