<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v2.ControllerConfig</code>
 */
class ControllerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 1;</code>
     */
    protected $project_generate_queue_id = 0;
    /**
     * Generated from protobuf field <code>repeated .schema.v2.ControllerConfig.Controller controllers = 2;</code>
     */
    private $controllers;
    /**
     * Generated from protobuf field <code>string source_path = 3;</code>
     */
    protected $source_path = '';
    /**
     * Generated from protobuf field <code>.schema.v2.ProjectSource project_source = 4;</code>
     */
    protected $project_source = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $project_generate_queue_id
     *     @type array<\Schema\V2\ControllerConfig\Controller>|\Google\Protobuf\Internal\RepeatedField $controllers
     *     @type string $source_path
     *     @type \Schema\V2\ProjectSource $project_source
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\ProjectSource::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 1;</code>
     * @return int
     */
    public function getProjectGenerateQueueId()
    {
        return $this->project_generate_queue_id;
    }

    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProjectGenerateQueueId($var)
    {
        GPBUtil::checkInt32($var);
        $this->project_generate_queue_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.ControllerConfig.Controller controllers = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getControllers()
    {
        return $this->controllers;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.ControllerConfig.Controller controllers = 2;</code>
     * @param array<\Schema\V2\ControllerConfig\Controller>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setControllers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V2\ControllerConfig\Controller::class);
        $this->controllers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_path = 3;</code>
     * @return string
     */
    public function getSourcePath()
    {
        return $this->source_path;
    }

    /**
     * Generated from protobuf field <code>string source_path = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSourcePath($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v2.ProjectSource project_source = 4;</code>
     * @return \Schema\V2\ProjectSource|null
     */
    public function getProjectSource()
    {
        return $this->project_source;
    }

    public function hasProjectSource()
    {
        return isset($this->project_source);
    }

    public function clearProjectSource()
    {
        unset($this->project_source);
    }

    /**
     * Generated from protobuf field <code>.schema.v2.ProjectSource project_source = 4;</code>
     * @param \Schema\V2\ProjectSource $var
     * @return $this
     */
    public function setProjectSource($var)
    {
        GPBUtil::checkMessage($var, \Schema\V2\ProjectSource::class);
        $this->project_source = $var;

        return $this;
    }

}

