<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\ControllerConfig\Controller\Endpoint instead.
     * @deprecated
     */
    class ControllerConfig_Controller_Endpoint {}
}
class_exists(ControllerConfig\Controller\Endpoint::class);
@trigger_error('Schema\V2\ControllerConfig_Controller_Endpoint is deprecated and will be removed in the next major release. Use Schema\V2\ControllerConfig\Controller\Endpoint instead', E_USER_DEPRECATED);

