<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\ERDConfig\Table instead.
     * @deprecated
     */
    class ERDConfig_Table {}
}
class_exists(ERDConfig\Table::class);
@trigger_error('Schema\V2\ERDConfig_Table is deprecated and will be removed in the next major release. Use Schema\V2\ERDConfig\Table instead', E_USER_DEPRECATED);

