<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\ERDConfig\Local instead.
     * @deprecated
     */
    class ERDConfig_Local {}
}
class_exists(ERDConfig\Local::class);
@trigger_error('Schema\V2\ERDConfig_Local is deprecated and will be removed in the next major release. Use Schema\V2\ERDConfig\Local instead', E_USER_DEPRECATED);

