<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_figma.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\ProjectFigmaImportResponse\Module instead.
     * @deprecated
     */
    class ProjectFigmaImportResponse_Module {}
}
class_exists(ProjectFigmaImportResponse\Module::class);
@trigger_error('Schema\V2\ProjectFigmaImportResponse_Module is deprecated and will be removed in the next major release. Use Schema\V2\ProjectFigmaImportResponse\Module instead', E_USER_DEPRECATED);

