<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_figma.proto

namespace Schema\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v2.ProjectFigmaImportRequest</code>
 */
class ProjectFigmaImportRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 1;</code>
     */
    protected $project_generate_queue_id = 0;
    /**
     * Generated from protobuf field <code>int32 project_id = 2;</code>
     */
    protected $project_id = 0;
    /**
     * Generated from protobuf field <code>string access_token = 3;</code>
     */
    protected $access_token = '';
    /**
     * Generated from protobuf field <code>string node_ids = 4;</code>
     */
    protected $node_ids = '';
    /**
     * Generated from protobuf field <code>string file_key = 5;</code>
     */
    protected $file_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $project_generate_queue_id
     *     @type int $project_id
     *     @type string $access_token
     *     @type string $node_ids
     *     @type string $file_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\ProjectFigma::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 1;</code>
     * @return int
     */
    public function getProjectGenerateQueueId()
    {
        return $this->project_generate_queue_id;
    }

    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProjectGenerateQueueId($var)
    {
        GPBUtil::checkInt32($var);
        $this->project_generate_queue_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 project_id = 2;</code>
     * @return int
     */
    public function getProjectId()
    {
        return $this->project_id;
    }

    /**
     * Generated from protobuf field <code>int32 project_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setProjectId($var)
    {
        GPBUtil::checkInt32($var);
        $this->project_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string access_token = 3;</code>
     * @return string
     */
    public function getAccessToken()
    {
        return $this->access_token;
    }

    /**
     * Generated from protobuf field <code>string access_token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAccessToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string node_ids = 4;</code>
     * @return string
     */
    public function getNodeIds()
    {
        return $this->node_ids;
    }

    /**
     * Generated from protobuf field <code>string node_ids = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNodeIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->node_ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string file_key = 5;</code>
     * @return string
     */
    public function getFileKey()
    {
        return $this->file_key;
    }

    /**
     * Generated from protobuf field <code>string file_key = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFileKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->file_key = $var;

        return $this;
    }

}

