<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_generate_queue.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\ProjectGenerateReport\Error instead.
     * @deprecated
     */
    class ProjectGenerateReport_Error {}
}
class_exists(ProjectGenerateReport\Error::class);
@trigger_error('Schema\V2\ProjectGenerateReport_Error is deprecated and will be removed in the next major release. Use Schema\V2\ProjectGenerateReport\Error instead', E_USER_DEPRECATED);

