<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\UseCaseRemoval\Block instead.
     * @deprecated
     */
    class UseCaseRemoval_Block {}
}
class_exists(UseCaseRemoval\Block::class);
@trigger_error('Schema\V2\UseCaseRemoval_Block is deprecated and will be removed in the next major release. Use Schema\V2\UseCaseRemoval\Block instead', E_USER_DEPRECATED);

