<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v2.UseCaseRemoval</code>
 */
class UseCaseRemoval extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.schema.v2.ProjectSource project_source = 1;</code>
     */
    protected $project_source = null;
    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 2;</code>
     */
    protected $project_generate_queue_id = 0;
    /**
     * Generated from protobuf field <code>.schema.v2.Git git = 3;</code>
     */
    protected $git = null;
    /**
     * Generated from protobuf field <code>optional .schema.v2.ImportBy import_by = 4;</code>
     */
    protected $import_by = null;
    /**
     * Generated from protobuf field <code>repeated .schema.v2.UseCaseRemoval.Block use_case_blocks = 5;</code>
     */
    private $use_case_blocks;
    /**
     * Generated from protobuf field <code>repeated .schema.v2.UseCaseRemoval.Block business_logic_blocks = 6;</code>
     */
    private $business_logic_blocks;
    /**
     * Generated from protobuf field <code>repeated .schema.v2.UseCaseRemoval.Block api_blocks = 7;</code>
     */
    private $api_blocks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Schema\V2\ProjectSource $project_source
     *     @type int $project_generate_queue_id
     *     @type \Schema\V2\Git $git
     *     @type int $import_by
     *     @type array<\Schema\V2\UseCaseRemoval\Block>|\Google\Protobuf\Internal\RepeatedField $use_case_blocks
     *     @type array<\Schema\V2\UseCaseRemoval\Block>|\Google\Protobuf\Internal\RepeatedField $business_logic_blocks
     *     @type array<\Schema\V2\UseCaseRemoval\Block>|\Google\Protobuf\Internal\RepeatedField $api_blocks
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\ProjectSource::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.schema.v2.ProjectSource project_source = 1;</code>
     * @return \Schema\V2\ProjectSource|null
     */
    public function getProjectSource()
    {
        return $this->project_source;
    }

    public function hasProjectSource()
    {
        return isset($this->project_source);
    }

    public function clearProjectSource()
    {
        unset($this->project_source);
    }

    /**
     * Generated from protobuf field <code>.schema.v2.ProjectSource project_source = 1;</code>
     * @param \Schema\V2\ProjectSource $var
     * @return $this
     */
    public function setProjectSource($var)
    {
        GPBUtil::checkMessage($var, \Schema\V2\ProjectSource::class);
        $this->project_source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 2;</code>
     * @return int
     */
    public function getProjectGenerateQueueId()
    {
        return $this->project_generate_queue_id;
    }

    /**
     * Generated from protobuf field <code>int32 project_generate_queue_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setProjectGenerateQueueId($var)
    {
        GPBUtil::checkInt32($var);
        $this->project_generate_queue_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v2.Git git = 3;</code>
     * @return \Schema\V2\Git|null
     */
    public function getGit()
    {
        return $this->git;
    }

    public function hasGit()
    {
        return isset($this->git);
    }

    public function clearGit()
    {
        unset($this->git);
    }

    /**
     * Generated from protobuf field <code>.schema.v2.Git git = 3;</code>
     * @param \Schema\V2\Git $var
     * @return $this
     */
    public function setGit($var)
    {
        GPBUtil::checkMessage($var, \Schema\V2\Git::class);
        $this->git = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .schema.v2.ImportBy import_by = 4;</code>
     * @return int
     */
    public function getImportBy()
    {
        return isset($this->import_by) ? $this->import_by : 0;
    }

    public function hasImportBy()
    {
        return isset($this->import_by);
    }

    public function clearImportBy()
    {
        unset($this->import_by);
    }

    /**
     * Generated from protobuf field <code>optional .schema.v2.ImportBy import_by = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setImportBy($var)
    {
        GPBUtil::checkEnum($var, \Schema\V2\ImportBy::class);
        $this->import_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.UseCaseRemoval.Block use_case_blocks = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUseCaseBlocks()
    {
        return $this->use_case_blocks;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.UseCaseRemoval.Block use_case_blocks = 5;</code>
     * @param array<\Schema\V2\UseCaseRemoval\Block>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUseCaseBlocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V2\UseCaseRemoval\Block::class);
        $this->use_case_blocks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.UseCaseRemoval.Block business_logic_blocks = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBusinessLogicBlocks()
    {
        return $this->business_logic_blocks;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.UseCaseRemoval.Block business_logic_blocks = 6;</code>
     * @param array<\Schema\V2\UseCaseRemoval\Block>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBusinessLogicBlocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V2\UseCaseRemoval\Block::class);
        $this->business_logic_blocks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.UseCaseRemoval.Block api_blocks = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApiBlocks()
    {
        return $this->api_blocks;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v2.UseCaseRemoval.Block api_blocks = 7;</code>
     * @param array<\Schema\V2\UseCaseRemoval\Block>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApiBlocks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V2\UseCaseRemoval\Block::class);
        $this->api_blocks = $arr;

        return $this;
    }

}

