<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/user_case_creation.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\UserCaseCreation\Error instead.
     * @deprecated
     */
    class UserCaseCreation_Error {}
}
class_exists(UserCaseCreation\Error::class);
@trigger_error('Schema\V2\UserCaseCreation_Error is deprecated and will be removed in the next major release. Use Schema\V2\UserCaseCreation\Error instead', E_USER_DEPRECATED);

