<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/user_case_creation.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\UserCase\Property instead.
     * @deprecated
     */
    class UserCase_Property {}
}
class_exists(UserCase\Property::class);
@trigger_error('Schema\V2\UserCase_Property is deprecated and will be removed in the next major release. Use Schema\V2\UserCase\Property instead', E_USER_DEPRECATED);

