<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/user_case_creation.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\UserCaseCreationResponse\Status instead.
     * @deprecated
     */
    class UserCaseCreationResponse_Status {}
}
class_exists(UserCaseCreationResponse\Status::class);
@trigger_error('Schema\V2\UserCaseCreationResponse_Status is deprecated and will be removed in the next major release. Use Schema\V2\UserCaseCreationResponse\Status instead', E_USER_DEPRECATED);

