<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/user_case_creation.proto

namespace Schema\V2;

if (false) {
    /**
     * This class is deprecated. Use Schema\V2\UserCaseCreation\ProjectTable instead.
     * @deprecated
     */
    class UserCaseCreation_ProjectTable {}
}
class_exists(UserCaseCreation\ProjectTable::class);
@trigger_error('Schema\V2\UserCaseCreation_ProjectTable is deprecated and will be removed in the next major release. Use Schema\V2\UserCaseCreation\ProjectTable instead', E_USER_DEPRECATED);

