<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Schema\V1\Controller\ResourceCondition;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.Controller.ResourceCondition.Expr</code>
 */
class Expr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string paths = 1;</code>
     */
    private $paths;
    /**
     * Generated from protobuf field <code>.schema.v1.DataType data_type = 8;</code>
     */
    protected $data_type = null;
    /**
     * Generated from protobuf field <code>.schema.v1.Operator operator = 9;</code>
     */
    protected $operator = 0;
    protected $map_to;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $paths
     *     @type string $query
     *     @type string $params
     *     @type string $body
     *     @type string $value
     *     @type int $system
     *     @type \Schema\V1\DataType $data_type
     *     @type int $operator
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string paths = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPaths()
    {
        return $this->paths;
    }

    /**
     * Generated from protobuf field <code>repeated string paths = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPaths($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->paths = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string query = 2;</code>
     * @return string
     */
    public function getQuery()
    {
        return $this->readOneof(2);
    }

    public function hasQuery()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>string query = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string params = 3;</code>
     * @return string
     */
    public function getParams()
    {
        return $this->readOneof(3);
    }

    public function hasParams()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>string params = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParams($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 4;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->readOneof(4);
    }

    public function hasBody()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>string body = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 5;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->readOneof(5);
    }

    public function hasValue()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>string value = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Controller.ResourceCondition.System system = 7;</code>
     * @return int
     */
    public function getSystem()
    {
        return $this->readOneof(7);
    }

    public function hasSystem()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Controller.ResourceCondition.System system = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSystem($var)
    {
        GPBUtil::checkEnum($var, \Schema\V1\Controller\ResourceCondition\System::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.DataType data_type = 8;</code>
     * @return \Schema\V1\DataType|null
     */
    public function getDataType()
    {
        return $this->data_type;
    }

    public function hasDataType()
    {
        return isset($this->data_type);
    }

    public function clearDataType()
    {
        unset($this->data_type);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.DataType data_type = 8;</code>
     * @param \Schema\V1\DataType $var
     * @return $this
     */
    public function setDataType($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\DataType::class);
        $this->data_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Operator operator = 9;</code>
     * @return int
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Operator operator = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkEnum($var, \Schema\V1\Operator::class);
        $this->operator = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getMapTo()
    {
        return $this->whichOneof("map_to");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Expr::class, \Schema\V1\Controller_ResourceCondition_Expr::class);

