<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Schema\V1\Table;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.Table.Column</code>
 */
class Column extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>.schema.v1.Table.Column.ColumnType type = 2;</code>
     */
    protected $type = null;
    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Constraint constraints = 3;</code>
     */
    private $constraints;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \Schema\V1\Table\Column\ColumnType $type
     *     @type array<\Schema\V1\Table\Constraint>|\Google\Protobuf\Internal\RepeatedField $constraints
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Table.Column.ColumnType type = 2;</code>
     * @return \Schema\V1\Table\Column\ColumnType|null
     */
    public function getType()
    {
        return $this->type;
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Table.Column.ColumnType type = 2;</code>
     * @param \Schema\V1\Table\Column\ColumnType $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\Table\Column\ColumnType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Constraint constraints = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConstraints()
    {
        return $this->constraints;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Constraint constraints = 3;</code>
     * @param array<\Schema\V1\Table\Constraint>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConstraints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\Table\Constraint::class);
        $this->constraints = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Column::class, \Schema\V1\Table_Column::class);

