<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1\NodeAction;

use UnexpectedValueException;

/**
 * Protobuf type <code>schema.v1.NodeAction.ActionType</code>
 */
class ActionType
{
    /**
     * Generated from protobuf enum <code>API = 0;</code>
     */
    const API = 0;
    /**
     * Generated from protobuf enum <code>GENERAL = 1;</code>
     */
    const GENERAL = 1;

    private static $valueToName = [
        self::API => 'API',
        self::GENERAL => 'GENERAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ActionType::class, \Schema\V1\NodeAction_ActionType::class);

