<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_source.proto

namespace Schema\V2\BlockChanges\Block;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v2.BlockChanges.Block.Modification</code>
 */
class Modification extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.schema.v2.BlockChanges.BlockBody deletion = 1;</code>
     */
    protected $deletion = null;
    /**
     * Generated from protobuf field <code>.schema.v2.BlockChanges.BlockBody addition = 2;</code>
     */
    protected $addition = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Schema\V2\BlockChanges\BlockBody $deletion
     *     @type \Schema\V2\BlockChanges\BlockBody $addition
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\ProjectSource::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.schema.v2.BlockChanges.BlockBody deletion = 1;</code>
     * @return \Schema\V2\BlockChanges\BlockBody|null
     */
    public function getDeletion()
    {
        return $this->deletion;
    }

    public function hasDeletion()
    {
        return isset($this->deletion);
    }

    public function clearDeletion()
    {
        unset($this->deletion);
    }

    /**
     * Generated from protobuf field <code>.schema.v2.BlockChanges.BlockBody deletion = 1;</code>
     * @param \Schema\V2\BlockChanges\BlockBody $var
     * @return $this
     */
    public function setDeletion($var)
    {
        GPBUtil::checkMessage($var, \Schema\V2\BlockChanges\BlockBody::class);
        $this->deletion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v2.BlockChanges.BlockBody addition = 2;</code>
     * @return \Schema\V2\BlockChanges\BlockBody|null
     */
    public function getAddition()
    {
        return $this->addition;
    }

    public function hasAddition()
    {
        return isset($this->addition);
    }

    public function clearAddition()
    {
        unset($this->addition);
    }

    /**
     * Generated from protobuf field <code>.schema.v2.BlockChanges.BlockBody addition = 2;</code>
     * @param \Schema\V2\BlockChanges\BlockBody $var
     * @return $this
     */
    public function setAddition($var)
    {
        GPBUtil::checkMessage($var, \Schema\V2\BlockChanges\BlockBody::class);
        $this->addition = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Modification::class, \Schema\V2\BlockChanges_Block_Modification::class);

