<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\AppPage\PageType instead.
     * @deprecated
     */
    class AppPage_PageType {}
}
class_exists(AppPage\PageType::class);
@trigger_error('Schema\V1\AppPage_PageType is deprecated and will be removed in the next major release. Use Schema\V1\AppPage\PageType instead', E_USER_DEPRECATED);

