<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.CodePreview</code>
 */
class CodePreview extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>optional .schema.v1.Backend backend = 2;</code>
     */
    protected $backend = null;
    /**
     * Generated from protobuf field <code>optional .schema.v1.WebApp web_app = 3;</code>
     */
    protected $web_app = null;
    /**
     * Generated from protobuf field <code>repeated string sections = 4;</code>
     */
    private $sections;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type \Schema\V1\Backend $backend
     *     @type \Schema\V1\WebApp $web_app
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $sections
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .schema.v1.Backend backend = 2;</code>
     * @return \Schema\V1\Backend|null
     */
    public function getBackend()
    {
        return $this->backend;
    }

    public function hasBackend()
    {
        return isset($this->backend);
    }

    public function clearBackend()
    {
        unset($this->backend);
    }

    /**
     * Generated from protobuf field <code>optional .schema.v1.Backend backend = 2;</code>
     * @param \Schema\V1\Backend $var
     * @return $this
     */
    public function setBackend($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\Backend::class);
        $this->backend = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .schema.v1.WebApp web_app = 3;</code>
     * @return \Schema\V1\WebApp|null
     */
    public function getWebApp()
    {
        return $this->web_app;
    }

    public function hasWebApp()
    {
        return isset($this->web_app);
    }

    public function clearWebApp()
    {
        unset($this->web_app);
    }

    /**
     * Generated from protobuf field <code>optional .schema.v1.WebApp web_app = 3;</code>
     * @param \Schema\V1\WebApp $var
     * @return $this
     */
    public function setWebApp($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\WebApp::class);
        $this->web_app = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string sections = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSections()
    {
        return $this->sections;
    }

    /**
     * Generated from protobuf field <code>repeated string sections = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSections($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->sections = $arr;

        return $this;
    }

}

