<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Controller\Authorization instead.
     * @deprecated
     */
    class Controller_Authorization {}
}
class_exists(Controller\Authorization::class);
@trigger_error('Schema\V1\Controller_Authorization is deprecated and will be removed in the next major release. Use Schema\V1\Controller\Authorization instead', E_USER_DEPRECATED);

