<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Controller\Endpoint\Get instead.
     * @deprecated
     */
    class Controller_Endpoint_Get {}
}
class_exists(Controller\Endpoint\Get::class);
@trigger_error('Schema\V1\Controller_Endpoint_Get is deprecated and will be removed in the next major release. Use Schema\V1\Controller\Endpoint\Get instead', E_USER_DEPRECATED);

