<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Controller\Response\Field instead.
     * @deprecated
     */
    class Controller_Response_Field {}
}
class_exists(Controller\Response\Field::class);
@trigger_error('Schema\V1\Controller_Response_Field is deprecated and will be removed in the next major release. Use Schema\V1\Controller\Response\Field instead', E_USER_DEPRECATED);

