<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Controller\ResourceCondition\Operand instead.
     * @deprecated
     */
    class Controller_ResourceCondition_Operand {}
}
class_exists(Controller\ResourceCondition\Operand::class);
@trigger_error('Schema\V1\Controller_ResourceCondition_Operand is deprecated and will be removed in the next major release. Use Schema\V1\Controller\ResourceCondition\Operand instead', E_USER_DEPRECATED);

