<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Controller\ResourceCondition instead.
     * @deprecated
     */
    class Controller_ResourceCondition {}
}
class_exists(Controller\ResourceCondition::class);
@trigger_error('Schema\V1\Controller_ResourceCondition is deprecated and will be removed in the next major release. Use Schema\V1\Controller\ResourceCondition instead', E_USER_DEPRECATED);

