<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Feature\GoogleTagManager instead.
     * @deprecated
     */
    class Feature_GoogleTagManager {}
}
class_exists(Feature\GoogleTagManager::class);
@trigger_error('Schema\V1\Feature_GoogleTagManager is deprecated and will be removed in the next major release. Use Schema\V1\Feature\GoogleTagManager instead', E_USER_DEPRECATED);

