<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Feature\Environment instead.
     * @deprecated
     */
    class Feature_Environment {}
}
class_exists(Feature\Environment::class);
@trigger_error('Schema\V1\Feature_Environment is deprecated and will be removed in the next major release. Use Schema\V1\Feature\Environment instead', E_USER_DEPRECATED);

