<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.FormValidation</code>
 */
class FormValidation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.schema.v1.FormValidation.ValidationType validation_type = 1;</code>
     */
    protected $validation_type = 0;
    /**
     * Generated from protobuf field <code>repeated .schema.v1.FormValidation.FormValidationsRule validation_rules = 2;</code>
     */
    private $validation_rules;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $validation_type
     *     @type array<\Schema\V1\FormValidation\FormValidationsRule>|\Google\Protobuf\Internal\RepeatedField $validation_rules
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.FormValidation.ValidationType validation_type = 1;</code>
     * @return int
     */
    public function getValidationType()
    {
        return $this->validation_type;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.FormValidation.ValidationType validation_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setValidationType($var)
    {
        GPBUtil::checkEnum($var, \Schema\V1\FormValidation\ValidationType::class);
        $this->validation_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.FormValidation.FormValidationsRule validation_rules = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValidationRules()
    {
        return $this->validation_rules;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.FormValidation.FormValidationsRule validation_rules = 2;</code>
     * @param array<\Schema\V1\FormValidation\FormValidationsRule>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValidationRules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\FormValidation\FormValidationsRule::class);
        $this->validation_rules = $arr;

        return $this;
    }

}

