<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.GetBackendResponse</code>
 */
class GetBackendResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.schema.v1.Backend backend = 1;</code>
     */
    protected $backend = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Schema\V1\Backend $backend
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Backend backend = 1;</code>
     * @return \Schema\V1\Backend|null
     */
    public function getBackend()
    {
        return $this->backend;
    }

    public function hasBackend()
    {
        return isset($this->backend);
    }

    public function clearBackend()
    {
        unset($this->backend);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.Backend backend = 1;</code>
     * @param \Schema\V1\Backend $var
     * @return $this
     */
    public function setBackend($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\Backend::class);
        $this->backend = $var;

        return $this;
    }

}

