<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.ListAuthorizationsResponse</code>
 */
class ListAuthorizationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .schema.v1.Authorization authorizations = 1;</code>
     */
    private $authorizations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Schema\V1\Authorization>|\Google\Protobuf\Internal\RepeatedField $authorizations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Authorization authorizations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAuthorizations()
    {
        return $this->authorizations;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Authorization authorizations = 1;</code>
     * @param array<\Schema\V1\Authorization>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAuthorizations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\Authorization::class);
        $this->authorizations = $arr;

        return $this;
    }

}

