<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.ListMigrationsResponse</code>
 */
class ListMigrationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .schema.v1.Migration migrations = 1;</code>
     */
    private $migrations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Schema\V1\Migration>|\Google\Protobuf\Internal\RepeatedField $migrations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Migration migrations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMigrations()
    {
        return $this->migrations;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Migration migrations = 1;</code>
     * @param array<\Schema\V1\Migration>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMigrations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\Migration::class);
        $this->migrations = $arr;

        return $this;
    }

}

