<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.MigrationColumnDefinition</code>
 */
class MigrationColumnDefinition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string column_type = 2;</code>
     */
    protected $column_type = '';
    /**
     * Generated from protobuf field <code>bool required = 3;</code>
     */
    protected $required = false;
    /**
     * Generated from protobuf field <code>bool unique = 4;</code>
     */
    protected $unique = false;
    /**
     * Generated from protobuf field <code>string default_value = 5;</code>
     */
    protected $default_value = '';
    /**
     * Generated from protobuf field <code>string comment = 6;</code>
     */
    protected $comment = '';
    /**
     * Generated from protobuf field <code>string uuid = 7;</code>
     */
    protected $uuid = '';
    /**
     * Generated from protobuf field <code>string table_definition_uuid = 8;</code>
     */
    protected $table_definition_uuid = '';
    /**
     * Generated from protobuf field <code>optional bool custom_foreign_key = 9;</code>
     */
    protected $custom_foreign_key = null;
    /**
     * Generated from protobuf field <code>optional .schema.v1.TableMetaDataMigration table_definition = 10;</code>
     */
    protected $table_definition = null;
    /**
     * Generated from protobuf field <code>int32 id = 11;</code>
     */
    protected $id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $column_type
     *     @type bool $required
     *     @type bool $unique
     *     @type string $default_value
     *     @type string $comment
     *     @type string $uuid
     *     @type string $table_definition_uuid
     *     @type bool $custom_foreign_key
     *     @type \Schema\V1\TableMetaDataMigration $table_definition
     *     @type int $id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string column_type = 2;</code>
     * @return string
     */
    public function getColumnType()
    {
        return $this->column_type;
    }

    /**
     * Generated from protobuf field <code>string column_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setColumnType($var)
    {
        GPBUtil::checkString($var, True);
        $this->column_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool required = 3;</code>
     * @return bool
     */
    public function getRequired()
    {
        return $this->required;
    }

    /**
     * Generated from protobuf field <code>bool required = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->required = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool unique = 4;</code>
     * @return bool
     */
    public function getUnique()
    {
        return $this->unique;
    }

    /**
     * Generated from protobuf field <code>bool unique = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setUnique($var)
    {
        GPBUtil::checkBool($var);
        $this->unique = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string default_value = 5;</code>
     * @return string
     */
    public function getDefaultValue()
    {
        return $this->default_value;
    }

    /**
     * Generated from protobuf field <code>string default_value = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDefaultValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->default_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string comment = 6;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Generated from protobuf field <code>string comment = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uuid = 7;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>string uuid = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string table_definition_uuid = 8;</code>
     * @return string
     */
    public function getTableDefinitionUuid()
    {
        return $this->table_definition_uuid;
    }

    /**
     * Generated from protobuf field <code>string table_definition_uuid = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTableDefinitionUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_definition_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool custom_foreign_key = 9;</code>
     * @return bool
     */
    public function getCustomForeignKey()
    {
        return isset($this->custom_foreign_key) ? $this->custom_foreign_key : false;
    }

    public function hasCustomForeignKey()
    {
        return isset($this->custom_foreign_key);
    }

    public function clearCustomForeignKey()
    {
        unset($this->custom_foreign_key);
    }

    /**
     * Generated from protobuf field <code>optional bool custom_foreign_key = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setCustomForeignKey($var)
    {
        GPBUtil::checkBool($var);
        $this->custom_foreign_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .schema.v1.TableMetaDataMigration table_definition = 10;</code>
     * @return \Schema\V1\TableMetaDataMigration|null
     */
    public function getTableDefinition()
    {
        return $this->table_definition;
    }

    public function hasTableDefinition()
    {
        return isset($this->table_definition);
    }

    public function clearTableDefinition()
    {
        unset($this->table_definition);
    }

    /**
     * Generated from protobuf field <code>optional .schema.v1.TableMetaDataMigration table_definition = 10;</code>
     * @param \Schema\V1\TableMetaDataMigration $var
     * @return $this
     */
    public function setTableDefinition($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\TableMetaDataMigration::class);
        $this->table_definition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 id = 11;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

}

