<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.NodeVariable</code>
 */
class NodeVariable extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string local_id = 1;</code>
     */
    protected $local_id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string value = 3;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>string value_path = 4;</code>
     */
    protected $value_path = '';
    /**
     * Generated from protobuf field <code>string default_value = 5;</code>
     */
    protected $default_value = '';
    /**
     * Generated from protobuf field <code>string value_type = 6;</code>
     */
    protected $value_type = '';
    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable.VariableDefaultType default_type = 7;</code>
     */
    protected $default_type = 0;
    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable.VariableSource source = 8;</code>
     */
    protected $source = 0;
    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable.VariableType variable_type = 9;</code>
     */
    protected $variable_type = 0;
    /**
     * Generated from protobuf field <code>repeated .schema.v1.NodeReference values = 10;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $local_id
     *     @type string $name
     *     @type string $value
     *     @type string $value_path
     *     @type string $default_value
     *     @type string $value_type
     *     @type int $default_type
     *     @type int $source
     *     @type int $variable_type
     *     @type array<\Schema\V1\NodeReference>|\Google\Protobuf\Internal\RepeatedField $values
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string local_id = 1;</code>
     * @return string
     */
    public function getLocalId()
    {
        return $this->local_id;
    }

    /**
     * Generated from protobuf field <code>string local_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLocalId($var)
    {
        GPBUtil::checkString($var, True);
        $this->local_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value_path = 4;</code>
     * @return string
     */
    public function getValuePath()
    {
        return $this->value_path;
    }

    /**
     * Generated from protobuf field <code>string value_path = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setValuePath($var)
    {
        GPBUtil::checkString($var, True);
        $this->value_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string default_value = 5;</code>
     * @return string
     */
    public function getDefaultValue()
    {
        return $this->default_value;
    }

    /**
     * Generated from protobuf field <code>string default_value = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDefaultValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->default_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value_type = 6;</code>
     * @return string
     */
    public function getValueType()
    {
        return $this->value_type;
    }

    /**
     * Generated from protobuf field <code>string value_type = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setValueType($var)
    {
        GPBUtil::checkString($var, True);
        $this->value_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable.VariableDefaultType default_type = 7;</code>
     * @return int
     */
    public function getDefaultType()
    {
        return $this->default_type;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable.VariableDefaultType default_type = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setDefaultType($var)
    {
        GPBUtil::checkEnum($var, \Schema\V1\NodeVariable\VariableDefaultType::class);
        $this->default_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable.VariableSource source = 8;</code>
     * @return int
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable.VariableSource source = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkEnum($var, \Schema\V1\NodeVariable\VariableSource::class);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable.VariableType variable_type = 9;</code>
     * @return int
     */
    public function getVariableType()
    {
        return $this->variable_type;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable.VariableType variable_type = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setVariableType($var)
    {
        GPBUtil::checkEnum($var, \Schema\V1\NodeVariable\VariableType::class);
        $this->variable_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.NodeReference values = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.NodeReference values = 10;</code>
     * @param array<\Schema\V1\NodeReference>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\NodeReference::class);
        $this->values = $arr;

        return $this;
    }

}

