<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.NodeParam</code>
 */
class NodeParam extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string param_type = 2;</code>
     */
    protected $param_type = '';
    /**
     * Generated from protobuf field <code>repeated string param_type_enum = 3;</code>
     */
    private $param_type_enum;
    /**
     * Generated from protobuf field <code>string default_value = 4;</code>
     */
    protected $default_value = '';
    /**
     * Generated from protobuf field <code>bool plural = 5;</code>
     */
    protected $plural = false;
    /**
     * Generated from protobuf field <code>bool automated = 6;</code>
     */
    protected $automated = false;
    /**
     * Generated from protobuf field <code>.schema.v1.NodeReference reference = 7;</code>
     */
    protected $reference = null;
    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable value = 8;</code>
     */
    protected $value = null;
    /**
     * Generated from protobuf field <code>repeated .schema.v1.NodeAction actions = 9;</code>
     */
    private $actions;
    /**
     * Generated from protobuf field <code>repeated .schema.v1.FunctionArgument function_arguments = 10;</code>
     */
    private $function_arguments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $param_type
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $param_type_enum
     *     @type string $default_value
     *     @type bool $plural
     *     @type bool $automated
     *     @type \Schema\V1\NodeReference $reference
     *     @type \Schema\V1\NodeVariable $value
     *     @type array<\Schema\V1\NodeAction>|\Google\Protobuf\Internal\RepeatedField $actions
     *     @type array<\Schema\V1\FunctionArgument>|\Google\Protobuf\Internal\RepeatedField $function_arguments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string param_type = 2;</code>
     * @return string
     */
    public function getParamType()
    {
        return $this->param_type;
    }

    /**
     * Generated from protobuf field <code>string param_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParamType($var)
    {
        GPBUtil::checkString($var, True);
        $this->param_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string param_type_enum = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParamTypeEnum()
    {
        return $this->param_type_enum;
    }

    /**
     * Generated from protobuf field <code>repeated string param_type_enum = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParamTypeEnum($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->param_type_enum = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string default_value = 4;</code>
     * @return string
     */
    public function getDefaultValue()
    {
        return $this->default_value;
    }

    /**
     * Generated from protobuf field <code>string default_value = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDefaultValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->default_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool plural = 5;</code>
     * @return bool
     */
    public function getPlural()
    {
        return $this->plural;
    }

    /**
     * Generated from protobuf field <code>bool plural = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setPlural($var)
    {
        GPBUtil::checkBool($var);
        $this->plural = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool automated = 6;</code>
     * @return bool
     */
    public function getAutomated()
    {
        return $this->automated;
    }

    /**
     * Generated from protobuf field <code>bool automated = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setAutomated($var)
    {
        GPBUtil::checkBool($var);
        $this->automated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeReference reference = 7;</code>
     * @return \Schema\V1\NodeReference|null
     */
    public function getReference()
    {
        return $this->reference;
    }

    public function hasReference()
    {
        return isset($this->reference);
    }

    public function clearReference()
    {
        unset($this->reference);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeReference reference = 7;</code>
     * @param \Schema\V1\NodeReference $var
     * @return $this
     */
    public function setReference($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\NodeReference::class);
        $this->reference = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable value = 8;</code>
     * @return \Schema\V1\NodeVariable|null
     */
    public function getValue()
    {
        return $this->value;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeVariable value = 8;</code>
     * @param \Schema\V1\NodeVariable $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\NodeVariable::class);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.NodeAction actions = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActions()
    {
        return $this->actions;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.NodeAction actions = 9;</code>
     * @param array<\Schema\V1\NodeAction>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\NodeAction::class);
        $this->actions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.FunctionArgument function_arguments = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFunctionArguments()
    {
        return $this->function_arguments;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.FunctionArgument function_arguments = 10;</code>
     * @param array<\Schema\V1\FunctionArgument>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFunctionArguments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\FunctionArgument::class);
        $this->function_arguments = $arr;

        return $this;
    }

}

