<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.PageNode</code>
 */
class PageNode extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string display_name = 2;</code>
     */
    protected $display_name = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string parent = 4;</code>
     */
    protected $parent = '';
    /**
     * Generated from protobuf field <code>repeated string nodes = 5;</code>
     */
    private $nodes;
    /**
     * Generated from protobuf field <code>map<string, string> linked_nodes = 6;</code>
     */
    private $linked_nodes;
    /**
     * Generated from protobuf field <code>string component_name = 7;</code>
     */
    protected $component_name = '';
    /**
     * Generated from protobuf field <code>.schema.v1.NodeCustom custom = 8;</code>
     */
    protected $custom = null;
    protected $props;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $display_name
     *     @type string $name
     *     @type string $parent
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $nodes
     *     @type array|\Google\Protobuf\Internal\MapField $linked_nodes
     *     @type string $component_name
     *     @type \Schema\V1\NodeCustom $custom
     *     @type \Schema\V1\WebNodeProps $web_props
     *     @type \Schema\V1\MobileNodeProps $mobile_props
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string display_name = 2;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Generated from protobuf field <code>string display_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parent = 4;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Generated from protobuf field <code>string parent = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string nodes = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNodes()
    {
        return $this->nodes;
    }

    /**
     * Generated from protobuf field <code>repeated string nodes = 5;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNodes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->nodes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> linked_nodes = 6;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getLinkedNodes()
    {
        return $this->linked_nodes;
    }

    /**
     * Generated from protobuf field <code>map<string, string> linked_nodes = 6;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setLinkedNodes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->linked_nodes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string component_name = 7;</code>
     * @return string
     */
    public function getComponentName()
    {
        return $this->component_name;
    }

    /**
     * Generated from protobuf field <code>string component_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setComponentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->component_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeCustom custom = 8;</code>
     * @return \Schema\V1\NodeCustom|null
     */
    public function getCustom()
    {
        return $this->custom;
    }

    public function hasCustom()
    {
        return isset($this->custom);
    }

    public function clearCustom()
    {
        unset($this->custom);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.NodeCustom custom = 8;</code>
     * @param \Schema\V1\NodeCustom $var
     * @return $this
     */
    public function setCustom($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\NodeCustom::class);
        $this->custom = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.WebNodeProps web_props = 9;</code>
     * @return \Schema\V1\WebNodeProps|null
     */
    public function getWebProps()
    {
        return $this->readOneof(9);
    }

    public function hasWebProps()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.WebNodeProps web_props = 9;</code>
     * @param \Schema\V1\WebNodeProps $var
     * @return $this
     */
    public function setWebProps($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\WebNodeProps::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.MobileNodeProps mobile_props = 10;</code>
     * @return \Schema\V1\MobileNodeProps|null
     */
    public function getMobileProps()
    {
        return $this->readOneof(10);
    }

    public function hasMobileProps()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.MobileNodeProps mobile_props = 10;</code>
     * @param \Schema\V1\MobileNodeProps $var
     * @return $this
     */
    public function setMobileProps($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\MobileNodeProps::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getProps()
    {
        return $this->whichOneof("props");
    }

}

