<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/project_import.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\ProjectAnalysisReport\Progress instead.
     * @deprecated
     */
    class ProjectAnalysisReport_Progress {}
}
class_exists(ProjectAnalysisReport\Progress::class);
@trigger_error('Schema\V1\ProjectAnalysisReport_Progress is deprecated and will be removed in the next major release. Use Schema\V1\ProjectAnalysisReport\Progress instead', E_USER_DEPRECATED);

