<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project_import.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.ProjectAnalysisReport</code>
 */
class ProjectAnalysisReport extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 project_import_id = 1;</code>
     */
    protected $project_import_id = 0;
    protected $state;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $project_import_id
     *     @type \Schema\V1\ProjectAnalysisReport\Progress $progress
     *     @type \Schema\V1\ProjectAnalysisReport\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProjectImport::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 project_import_id = 1;</code>
     * @return int
     */
    public function getProjectImportId()
    {
        return $this->project_import_id;
    }

    /**
     * Generated from protobuf field <code>int32 project_import_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProjectImportId($var)
    {
        GPBUtil::checkInt32($var);
        $this->project_import_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.ProjectAnalysisReport.Progress progress = 2;</code>
     * @return \Schema\V1\ProjectAnalysisReport\Progress|null
     */
    public function getProgress()
    {
        return $this->readOneof(2);
    }

    public function hasProgress()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.ProjectAnalysisReport.Progress progress = 2;</code>
     * @param \Schema\V1\ProjectAnalysisReport\Progress $var
     * @return $this
     */
    public function setProgress($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\ProjectAnalysisReport\Progress::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.ProjectAnalysisReport.Error error = 3;</code>
     * @return \Schema\V1\ProjectAnalysisReport\Error|null
     */
    public function getError()
    {
        return $this->readOneof(3);
    }

    public function hasError()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.ProjectAnalysisReport.Error error = 3;</code>
     * @param \Schema\V1\ProjectAnalysisReport\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\ProjectAnalysisReport\Error::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getState()
    {
        return $this->whichOneof("state");
    }

}

