<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/project_import.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\ProjectAnalysisReport\Error instead.
     * @deprecated
     */
    class ProjectAnalysisReport_Error {}
}
class_exists(ProjectAnalysisReport\Error::class);
@trigger_error('Schema\V1\ProjectAnalysisReport_Error is deprecated and will be removed in the next major release. Use Schema\V1\ProjectAnalysisReport\Error instead', E_USER_DEPRECATED);

