<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project_import.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.ProjectAnalysis</code>
 */
class ProjectAnalysis extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 project_import_id = 1;</code>
     */
    protected $project_import_id = 0;
    /**
     * Generated from protobuf field <code>string repo = 2;</code>
     */
    protected $repo = '';
    /**
     * Generated from protobuf field <code>string owner = 3;</code>
     */
    protected $owner = '';
    /**
     * Generated from protobuf field <code>string branch = 4;</code>
     */
    protected $branch = '';
    /**
     * Generated from protobuf field <code>string token = 5;</code>
     */
    protected $token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $project_import_id
     *     @type string $repo
     *     @type string $owner
     *     @type string $branch
     *     @type string $token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ProjectImport::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 project_import_id = 1;</code>
     * @return int
     */
    public function getProjectImportId()
    {
        return $this->project_import_id;
    }

    /**
     * Generated from protobuf field <code>int32 project_import_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProjectImportId($var)
    {
        GPBUtil::checkInt32($var);
        $this->project_import_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string repo = 2;</code>
     * @return string
     */
    public function getRepo()
    {
        return $this->repo;
    }

    /**
     * Generated from protobuf field <code>string repo = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRepo($var)
    {
        GPBUtil::checkString($var, True);
        $this->repo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner = 3;</code>
     * @return string
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * Generated from protobuf field <code>string owner = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string branch = 4;</code>
     * @return string
     */
    public function getBranch()
    {
        return $this->branch;
    }

    /**
     * Generated from protobuf field <code>string branch = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBranch($var)
    {
        GPBUtil::checkString($var, True);
        $this->branch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token = 5;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

}

