<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/project_import.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\ProjectAnalysisReport\Payload instead.
     * @deprecated
     */
    class ProjectAnalysisReport_Payload {}
}
class_exists(ProjectAnalysisReport\Payload::class);
@trigger_error('Schema\V1\ProjectAnalysisReport_Payload is deprecated and will be removed in the next major release. Use Schema\V1\ProjectAnalysisReport\Payload instead', E_USER_DEPRECATED);

