<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.RemoveTableRelation</code>
 */
class RemoveTableRelation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>string prev_uuid = 3;</code>
     */
    protected $prev_uuid = '';
    /**
     * Generated from protobuf field <code>string next_uuid = 4;</code>
     */
    protected $next_uuid = '';
    /**
     * Generated from protobuf field <code>.schema.v1.TableRelationMigration prev_record = 5;</code>
     */
    protected $prev_record = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type string $prev_uuid
     *     @type string $next_uuid
     *     @type \Schema\V1\TableRelationMigration $prev_record
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prev_uuid = 3;</code>
     * @return string
     */
    public function getPrevUuid()
    {
        return $this->prev_uuid;
    }

    /**
     * Generated from protobuf field <code>string prev_uuid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrevUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->prev_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string next_uuid = 4;</code>
     * @return string
     */
    public function getNextUuid()
    {
        return $this->next_uuid;
    }

    /**
     * Generated from protobuf field <code>string next_uuid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNextUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.schema.v1.TableRelationMigration prev_record = 5;</code>
     * @return \Schema\V1\TableRelationMigration|null
     */
    public function getPrevRecord()
    {
        return $this->prev_record;
    }

    public function hasPrevRecord()
    {
        return isset($this->prev_record);
    }

    public function clearPrevRecord()
    {
        unset($this->prev_record);
    }

    /**
     * Generated from protobuf field <code>.schema.v1.TableRelationMigration prev_record = 5;</code>
     * @param \Schema\V1\TableRelationMigration $var
     * @return $this
     */
    public function setPrevRecord($var)
    {
        GPBUtil::checkMessage($var, \Schema\V1\TableRelationMigration::class);
        $this->prev_record = $var;

        return $this;
    }

}

