<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\RenderCondition\Source instead.
     * @deprecated
     */
    class RenderCondition_Source {}
}
class_exists(RenderCondition\Source::class);
@trigger_error('Schema\V1\RenderCondition_Source is deprecated and will be removed in the next major release. Use Schema\V1\RenderCondition\Source instead', E_USER_DEPRECATED);

