<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\RenderCondition\Condition instead.
     * @deprecated
     */
    class RenderCondition_Condition {}
}
class_exists(RenderCondition\Condition::class);
@trigger_error('Schema\V1\RenderCondition_Condition is deprecated and will be removed in the next major release. Use Schema\V1\RenderCondition\Condition instead', E_USER_DEPRECATED);

