<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/project_export.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Report\Error instead.
     * @deprecated
     */
    class Report_Error {}
}
class_exists(Report\Error::class);
@trigger_error('Schema\V1\Report_Error is deprecated and will be removed in the next major release. Use Schema\V1\Report\Error instead', E_USER_DEPRECATED);

