<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/project_export.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Report\ProjectPreview instead.
     * @deprecated
     */
    class Report_ProjectPreview {}
}
class_exists(Report\ProjectPreview::class);
@trigger_error('Schema\V1\Report_ProjectPreview is deprecated and will be removed in the next major release. Use Schema\V1\Report\ProjectPreview instead', E_USER_DEPRECATED);

