<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Table\Index instead.
     * @deprecated
     */
    class Table_Index {}
}
class_exists(Table\Index::class);
@trigger_error('Schema\V1\Table_Index is deprecated and will be removed in the next major release. Use Schema\V1\Table\Index instead', E_USER_DEPRECATED);

