<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Table\ColumnValidationOption\LengthValidation instead.
     * @deprecated
     */
    class Table_ColumnValidationOption_LengthValidation {}
}
class_exists(Table\ColumnValidationOption\LengthValidation::class);
@trigger_error('Schema\V1\Table_ColumnValidationOption_LengthValidation is deprecated and will be removed in the next major release. Use Schema\V1\Table\ColumnValidationOption\LengthValidation instead', E_USER_DEPRECATED);

