<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Table\Column instead.
     * @deprecated
     */
    class Table_Column {}
}
class_exists(Table\Column::class);
@trigger_error('Schema\V1\Table_Column is deprecated and will be removed in the next major release. Use Schema\V1\Table\Column instead', E_USER_DEPRECATED);

