<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Table\Column\IntegerType instead.
     * @deprecated
     */
    class Table_Column_IntegerType {}
}
class_exists(Table\Column\IntegerType::class);
@trigger_error('Schema\V1\Table_Column_IntegerType is deprecated and will be removed in the next major release. Use Schema\V1\Table\Column\IntegerType instead', E_USER_DEPRECATED);

