<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Table\ColumnValidation instead.
     * @deprecated
     */
    class Table_ColumnValidation {}
}
class_exists(Table\ColumnValidation::class);
@trigger_error('Schema\V1\Table_ColumnValidation is deprecated and will be removed in the next major release. Use Schema\V1\Table\ColumnValidation instead', E_USER_DEPRECATED);

