<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Table\Column\StringType\Condition instead.
     * @deprecated
     */
    class Table_Column_StringType_Condition {}
}
class_exists(Table\Column\StringType\Condition::class);
@trigger_error('Schema\V1\Table_Column_StringType_Condition is deprecated and will be removed in the next major release. Use Schema\V1\Table\Column\StringType\Condition instead', E_USER_DEPRECATED);

