<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Table\ColumnValidationOption\NumericalityValidation instead.
     * @deprecated
     */
    class Table_ColumnValidationOption_NumericalityValidation {}
}
class_exists(Table\ColumnValidationOption\NumericalityValidation::class);
@trigger_error('Schema\V1\Table_ColumnValidationOption_NumericalityValidation is deprecated and will be removed in the next major release. Use Schema\V1\Table\ColumnValidationOption\NumericalityValidation instead', E_USER_DEPRECATED);

