<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Table\Column\DateType instead.
     * @deprecated
     */
    class Table_Column_DateType {}
}
class_exists(Table\Column\DateType::class);
@trigger_error('Schema\V1\Table_Column_DateType is deprecated and will be removed in the next major release. Use Schema\V1\Table\Column\DateType instead', E_USER_DEPRECATED);

