<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Table\Relation\RelationHasOne instead.
     * @deprecated
     */
    class Table_Relation_RelationHasOne {}
}
class_exists(Table\Relation\RelationHasOne::class);
@trigger_error('Schema\V1\Table_Relation_RelationHasOne is deprecated and will be removed in the next major release. Use Schema\V1\Table\Relation\RelationHasOne instead', E_USER_DEPRECATED);

