<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Table\Constraint\NotNull instead.
     * @deprecated
     */
    class Table_Constraint_NotNull {}
}
class_exists(Table\Constraint\NotNull::class);
@trigger_error('Schema\V1\Table_Constraint_NotNull is deprecated and will be removed in the next major release. Use Schema\V1\Table\Constraint\NotNull instead', E_USER_DEPRECATED);

