<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payloads.proto

namespace Schema\V1;

if (false) {
    /**
     * This class is deprecated. Use Schema\V1\Table\ColumnValidationOption\DateValidation instead.
     * @deprecated
     */
    class Table_ColumnValidationOption_DateValidation {}
}
class_exists(Table\ColumnValidationOption\DateValidation::class);
@trigger_error('Schema\V1\Table_ColumnValidationOption_DateValidation is deprecated and will be removed in the next major release. Use Schema\V1\Table\ColumnValidationOption\DateValidation instead', E_USER_DEPRECATED);

