<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/business_logic.proto

namespace Schema\V2\BusinessLogic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v2.BusinessLogic.Property</code>
 */
class Property extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 use_case_id = 1;</code>
     */
    protected $use_case_id = null;
    /**
     * Generated from protobuf field <code>optional string category = 2;</code>
     */
    protected $category = null;
    /**
     * Generated from protobuf field <code>optional int32 level = 3;</code>
     */
    protected $level = null;
    /**
     * Generated from protobuf field <code>optional string text_color = 4;</code>
     */
    protected $text_color = null;
    /**
     * Generated from protobuf field <code>optional string background_color = 5;</code>
     */
    protected $background_color = null;
    /**
     * Generated from protobuf field <code>optional string text_alignment = 6;</code>
     */
    protected $text_alignment = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $use_case_id
     *     @type string $category
     *     @type int $level
     *     @type string $text_color
     *     @type string $background_color
     *     @type string $text_alignment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V2\BusinessLogic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 use_case_id = 1;</code>
     * @return int
     */
    public function getUseCaseId()
    {
        return isset($this->use_case_id) ? $this->use_case_id : 0;
    }

    public function hasUseCaseId()
    {
        return isset($this->use_case_id);
    }

    public function clearUseCaseId()
    {
        unset($this->use_case_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 use_case_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUseCaseId($var)
    {
        GPBUtil::checkInt32($var);
        $this->use_case_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string category = 2;</code>
     * @return string
     */
    public function getCategory()
    {
        return isset($this->category) ? $this->category : '';
    }

    public function hasCategory()
    {
        return isset($this->category);
    }

    public function clearCategory()
    {
        unset($this->category);
    }

    /**
     * Generated from protobuf field <code>optional string category = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 level = 3;</code>
     * @return int
     */
    public function getLevel()
    {
        return isset($this->level) ? $this->level : 0;
    }

    public function hasLevel()
    {
        return isset($this->level);
    }

    public function clearLevel()
    {
        unset($this->level);
    }

    /**
     * Generated from protobuf field <code>optional int32 level = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string text_color = 4;</code>
     * @return string
     */
    public function getTextColor()
    {
        return isset($this->text_color) ? $this->text_color : '';
    }

    public function hasTextColor()
    {
        return isset($this->text_color);
    }

    public function clearTextColor()
    {
        unset($this->text_color);
    }

    /**
     * Generated from protobuf field <code>optional string text_color = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTextColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->text_color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string background_color = 5;</code>
     * @return string
     */
    public function getBackgroundColor()
    {
        return isset($this->background_color) ? $this->background_color : '';
    }

    public function hasBackgroundColor()
    {
        return isset($this->background_color);
    }

    public function clearBackgroundColor()
    {
        unset($this->background_color);
    }

    /**
     * Generated from protobuf field <code>optional string background_color = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBackgroundColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->background_color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string text_alignment = 6;</code>
     * @return string
     */
    public function getTextAlignment()
    {
        return isset($this->text_alignment) ? $this->text_alignment : '';
    }

    public function hasTextAlignment()
    {
        return isset($this->text_alignment);
    }

    public function clearTextAlignment()
    {
        unset($this->text_alignment);
    }

    /**
     * Generated from protobuf field <code>optional string text_alignment = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTextAlignment($var)
    {
        GPBUtil::checkString($var, True);
        $this->text_alignment = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Property::class, \Schema\V2\BusinessLogic_Property::class);

