# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/asset.proto

require 'google/protobuf'


descriptor_data = "\n\x0ev2/asset.proto\x12\tschema.v2\"\x1f\n\x05\x41sset\x12\x16\n\x0e\x62\x61se64_content\x18\x01 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Schema
  module V2
    Asset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.Asset").msgclass
  end
end
