# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/block.proto

require 'google/protobuf'


descriptor_data = "\n\x0ev2/block.proto\x12\tschema.v2\"\xbf\x01\n\x05\x42lock\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07node_id\x18\x03 \x01(\t\x12\x16\n\x0eparent_node_id\x18\x04 \x01(\t\x12\x14\n\x0cpage_node_id\x18\x05 \x01(\t\x12\x12\n\nblock_type\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\x12\x12\n\nproperties\x18\x08 \x01(\t\x12\x12\n\nproject_id\x18\t \x01(\x05\x12\x10\n\x08\x63hildren\x18\n \x03(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Schema
  module V2
    Block = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.Block").msgclass
  end
end
