# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/business_logic.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("v2/business_logic.proto", :syntax => :proto3) do
    add_message "schema.v2.BusinessLogicResponse" do
      optional :project_generate_queue_id, :int32, 1
      optional :project_id, :int32, 2
      repeated :business_logics, :message, 3, "schema.v2.BusinessLogic"
    end
    add_message "schema.v2.BusinessLogic" do
      optional :node_id, :string, 1
      optional :parent_node_id, :string, 2
      optional :page_node_id, :string, 3
      optional :block_type, :string, 4
      optional :name, :string, 5
      repeated :content, :message, 6, "schema.v2.BusinessLogic.Content"
      optional :properties, :message, 7, "schema.v2.BusinessLogic.Property"
      optional :project_id, :int32, 8
      repeated :children, :string, 9
    end
    add_message "schema.v2.BusinessLogic.Content" do
      optional :type, :string, 1
      optional :value, :string, 2
      optional :styles, :string, 3
    end
    add_message "schema.v2.BusinessLogic.Property" do
      proto3_optional :use_case_id, :string, 1
      proto3_optional :category, :string, 2
      proto3_optional :level, :int32, 3
      proto3_optional :text_color, :string, 4
      proto3_optional :background_color, :string, 5
      proto3_optional :text_alignment, :string, 6
    end
  end
end

module Schema
  module V2
    BusinessLogicResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.BusinessLogicResponse").msgclass
    BusinessLogic = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.BusinessLogic").msgclass
    BusinessLogic::Content = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.BusinessLogic.Content").msgclass
    BusinessLogic::Property = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.BusinessLogic.Property").msgclass
  end
end
