# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/generate_dynamic_doc_report.proto

require 'google/protobuf'


descriptor_data = "\n$v2/generate_dynamic_doc_report.proto\x12\tschema.v2\"\xc2\x01\n\x18GenerateDynamicDocReport\x12!\n\x19project_generate_queue_id\x18\x01 \x01(\x05\x12:\n\x06status\x18\x02 \x01(\x0e\x32*.schema.v2.GenerateDynamicDocReport.Status\x12\x15\n\rerror_message\x18\x03 \x01(\t\"0\n\x06Status\x12\x0b\n\x07STARTED\x10\x00\x12\r\n\tCOMPLETED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Schema
  module V2
    GenerateDynamicDocReport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.GenerateDynamicDocReport").msgclass
    GenerateDynamicDocReport::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.GenerateDynamicDocReport.Status").enummodule
  end
end
