# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_preview.proto

require 'google/protobuf'


descriptor_data = "\n\x18v2/project_preview.proto\x12\tschema.v2\x1a\x17v2/project_source.proto\"\x88\x02\n\x15ProjectPreviewRequest\x12\x1a\n\x12project_preview_id\x18\x01 \x01(\x05\x12\x12\n\nproject_id\x18\x02 \x01(\x05\x12\x30\n\x0eproject_source\x18\x03 \x01(\x0b\x32\x18.schema.v2.ProjectSource\x12\x1b\n\x03git\x18\x04 \x01(\x0b\x32\x0e.schema.v2.Git\x12\x32\n\x04logs\x18\x05 \x03(\x0b\x32$.schema.v2.ProjectPreviewRequest.Log\x1a<\n\x03Log\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\xcc\x01\n\x16ProjectPreviewResponse\x12\x1a\n\x12project_preview_id\x18\x01 \x01(\x05\x12\x12\n\nproject_id\x18\x02 \x01(\x05\x12\x38\n\x06status\x18\x04 \x01(\x0e\x32(.schema.v2.ProjectPreviewResponse.Status\x12\x13\n\x0btoken_usage\x18\x05 \x01(\x05\"3\n\x06Status\x12\r\n\tSUCCEEDED\x10\x00\x12\x0e\n\nINPROGRESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\"@\n\x18\x44\x65ployGenerateScriptItem\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\xe3\x01\n#ProjectPreviewDeployGenerateRequest\x12\x1a\n\x12project_preview_id\x18\x01 \x01(\x05\x12\x12\n\nproject_id\x18\x02 \x01(\x05\x12\x30\n\x0eproject_source\x18\x03 \x01(\x0b\x32\x18.schema.v2.ProjectSource\x12\x1b\n\x03git\x18\x04 \x01(\x0b\x32\x0e.schema.v2.Git\x12=\n\x10previous_scripts\x18\x05 \x03(\x0b\x32#.schema.v2.DeployGenerateScriptItem\"\xb7\x02\n$ProjectPreviewDeployGenerateResponse\x12\x1a\n\x12project_preview_id\x18\x01 \x01(\x05\x12\x12\n\nproject_id\x18\x02 \x01(\x05\x12\x46\n\x06status\x18\x04 \x01(\x0e\x32\x36.schema.v2.ProjectPreviewDeployGenerateResponse.Status\x12\x13\n\x0btoken_usage\x18\x05 \x01(\x05\x12\x34\n\x07scripts\x18\x06 \x03(\x0b\x32#.schema.v2.DeployGenerateScriptItem\x12\x17\n\x0f\x62\x61se_image_name\x18\x07 \x01(\t\"3\n\x06Status\x12\r\n\tSUCCEEDED\x10\x00\x12\x0e\n\nINPROGRESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Schema
  module V2
    ProjectPreviewRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectPreviewRequest").msgclass
    ProjectPreviewRequest::Log = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectPreviewRequest.Log").msgclass
    ProjectPreviewResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectPreviewResponse").msgclass
    ProjectPreviewResponse::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectPreviewResponse.Status").enummodule
    DeployGenerateScriptItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.DeployGenerateScriptItem").msgclass
    ProjectPreviewDeployGenerateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectPreviewDeployGenerateRequest").msgclass
    ProjectPreviewDeployGenerateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectPreviewDeployGenerateResponse").msgclass
    ProjectPreviewDeployGenerateResponse::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectPreviewDeployGenerateResponse.Status").enummodule
  end
end
