# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_figma.proto

require 'google/protobuf'

descriptor_data = "\n\x16v2/project_figma.proto\x12\tschema.v2\x1a\x11v2/document.proto\"\xaa\x01\n\x19ProjectFigmaImportRequest\x12!\n\x19project_generate_queue_id\x18\x01 \x01(\x05\x12\x12\n\nproject_id\x18\x02 \x01(\x05\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x10\n\x08node_ids\x18\x04 \x01(\t\x12\x10\n\x08\x66ile_key\x18\x05 \x01(\t\x12\x1c\n\x14master_language_code\x18\x06 \x01(\t\"\xb1\x01\n\x17ProjectFigmaSyncRequest\x12!\n\x19project_generate_queue_id\x18\x01 \x01(\x05\x12\x12\n\nproject_id\x18\x02 \x01(\x05\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12+\n\tdocuments\x18\x04 \x03(\x0b\x32\x18.schema.v2.core.Document\x12\x1c\n\x14master_language_code\x18\x05 \x01(\t\"\x8e\x03\n\x1aProjectFigmaImportResponse\x12!\n\x19project_generate_queue_id\x18\x01 \x01(\x05\x12\x12\n\nproject_id\x18\x02 \x01(\x05\x12\x33\n\tdocuments\x18\x03 \x03(\x0b\x32 .schema.v2.core.DocumentResponse\x12<\n\x06module\x18\x04 \x01(\x0e\x32,.schema.v2.ProjectFigmaImportResponse.Module\x12<\n\x06status\x18\x05 \x01(\x0e\x32,.schema.v2.ProjectFigmaImportResponse.Status\x12\x13\n\x0btoken_usage\x18\x06 \x01(\x05\x12\x15\n\rerror_message\x18\x07 \x01(\t\"\'\n\x06Module\x12\x1d\n\x19\x46IGMA_TO_NATURAL_LANGUAGE\x10\x00\"3\n\x06Status\x12\r\n\tSUCCEEDED\x10\x00\x12\x0e\n\nINPROGRESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\"\x1d\n\x05\x46igma\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Schema
  module V2
    ProjectFigmaImportRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectFigmaImportRequest").msgclass
    ProjectFigmaSyncRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectFigmaSyncRequest").msgclass
    ProjectFigmaImportResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectFigmaImportResponse").msgclass
    ProjectFigmaImportResponse::Module = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectFigmaImportResponse.Module").enummodule
    ProjectFigmaImportResponse::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectFigmaImportResponse.Status").enummodule
    Figma = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.Figma").msgclass
  end
end
