# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/project_pdf.proto

require 'google/protobuf'

descriptor_data = "\n\x14v2/project_pdf.proto\x12\tschema.v2\x1a\x11v2/document.proto\"\x8b\x01\n\x17ProjectPdfImportRequest\x12!\n\x19project_generate_queue_id\x18\x01 \x01(\x05\x12\x12\n\nproject_id\x18\x02 \x01(\x05\x12\x0c\n\x04\x66ile\x18\x03 \x01(\t\x12\x15\n\rsucceed_pages\x18\x04 \x03(\x05\x12\x14\n\x0c\x66\x61iled_pages\x18\x05 \x03(\x05\"\xc5\x03\n\x18ProjectPdfImportResponse\x12!\n\x19project_generate_queue_id\x18\x01 \x01(\x05\x12\x12\n\nproject_id\x18\x02 \x01(\x05\x12:\n\x06module\x18\x03 \x01(\x0e\x32*.schema.v2.ProjectPdfImportResponse.Module\x12:\n\x06status\x18\x04 \x01(\x0e\x32*.schema.v2.ProjectPdfImportResponse.Status\x12\x13\n\x0btoken_usage\x18\x05 \x01(\x05\x12\x33\n\tdocuments\x18\x06 \x03(\x0b\x32 .schema.v2.core.DocumentResponse\x12\x15\n\rerror_message\x18\x07 \x01(\t\x12\x15\n\rsucceed_pages\x18\x08 \x03(\x05\x12\x14\n\x0c\x66\x61iled_pages\x18\t \x03(\x05\x12\x10\n\x08language\x18\n \x01(\t\"%\n\x06Module\x12\x1b\n\x17PDF_TO_NATURAL_LANGUAGE\x10\x00\"3\n\x06Status\x12\r\n\tSUCCEEDED\x10\x00\x12\x0e\n\nINPROGRESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Schema
  module V2
    ProjectPdfImportRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectPdfImportRequest").msgclass
    ProjectPdfImportResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectPdfImportResponse").msgclass
    ProjectPdfImportResponse::Module = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectPdfImportResponse.Module").enummodule
    ProjectPdfImportResponse::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.ProjectPdfImportResponse.Status").enummodule
  end
end
