# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/session.proto

require 'google/protobuf'


descriptor_data = "\n\x10v2/session.proto\x12\tschema.v2\"\x1f\n\x07Session\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Schema
  module V2
    Session = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.Session").msgclass
  end
end
