# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/translation_blocks.proto

require 'google/protobuf'


descriptor_data = "\n\x1bv2/translation_blocks.proto\x12\tschema.v2\"\xab\x03\n\x11TranslationBlocks\x12!\n\x19project_generate_queue_id\x18\x01 \x01(\x05\x12\x12\n\nproject_id\x18\x02 \x01(\x05\x12\x44\n\x0flanguage_config\x18\x03 \x01(\x0b\x32+.schema.v2.TranslationBlocks.LanguageConfig\x12+\n\x06\x62locks\x18\x04 \x03(\x0b\x32\x1b.schema.v2.TranslationBlock\x12\x39\n\x08progress\x18\x05 \x01(\x0b\x32%.schema.v2.TranslationBlocks.ProgressH\x00\x12\x33\n\x05\x65rror\x18\x06 \x01(\x0b\x32\".schema.v2.TranslationBlocks.ErrorH\x00\x1a<\n\x0eLanguageConfig\x12\x15\n\rfrom_language\x18\x01 \x01(\t\x12\x13\n\x0bto_language\x18\x02 \x01(\t\x1a\x1b\n\x08Progress\x12\x0f\n\x07message\x18\x01 \x01(\t\x1a\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\tB\x07\n\x05state\"X\n\x10TranslationBlock\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x16\n\x0eparent_node_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x03(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Schema
  module V2
    TranslationBlocks = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.TranslationBlocks").msgclass
    TranslationBlocks::LanguageConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.TranslationBlocks.LanguageConfig").msgclass
    TranslationBlocks::Progress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.TranslationBlocks.Progress").msgclass
    TranslationBlocks::Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.TranslationBlocks.Error").msgclass
    TranslationBlock = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("schema.v2.TranslationBlock").msgclass
  end
end
