<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1\NodeVariable;

use UnexpectedValueException;

/**
 * Protobuf type <code>schema.v1.NodeVariable.VariableDefaultType</code>
 */
class VariableDefaultType
{
    /**
     * Generated from protobuf enum <code>STRING = 0;</code>
     */
    const STRING = 0;
    /**
     * Generated from protobuf enum <code>VARIABLE = 1;</code>
     */
    const VARIABLE = 1;

    private static $valueToName = [
        self::STRING => 'STRING',
        self::VARIABLE => 'VARIABLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(VariableDefaultType::class, \Schema\V1\NodeVariable_VariableDefaultType::class);

