<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Schema\V1\NodeVariable;

use UnexpectedValueException;

/**
 * Protobuf type <code>schema.v1.NodeVariable.VariableType</code>
 */
class VariableType
{
    /**
     * Generated from protobuf enum <code>STATIC = 0;</code>
     */
    const PBSTATIC = 0;
    /**
     * Generated from protobuf enum <code>DYNAMIC = 1;</code>
     */
    const DYNAMIC = 1;

    private static $valueToName = [
        self::PBSTATIC => 'STATIC',
        self::DYNAMIC => 'DYNAMIC',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            $pbconst =  __CLASS__. '::PB' . strtoupper($name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                        'Enum %s has no value defined for name %s', __CLASS__, $name));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(VariableType::class, \Schema\V1\NodeVariable_VariableType::class);

