<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Schema\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.Table</code>
 */
class Table extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Column columns = 2;</code>
     */
    private $columns;
    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Relation relations = 3;</code>
     */
    private $relations;
    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Index indexes = 4;</code>
     */
    private $indexes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type array<\Schema\V1\Table\Column>|\Google\Protobuf\Internal\RepeatedField $columns
     *     @type array<\Schema\V1\Table\Relation>|\Google\Protobuf\Internal\RepeatedField $relations
     *     @type array<\Schema\V1\Table\Index>|\Google\Protobuf\Internal\RepeatedField $indexes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Column columns = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Column columns = 2;</code>
     * @param array<\Schema\V1\Table\Column>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\Table\Column::class);
        $this->columns = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Relation relations = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRelations()
    {
        return $this->relations;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Relation relations = 3;</code>
     * @param array<\Schema\V1\Table\Relation>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRelations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\Table\Relation::class);
        $this->relations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Index indexes = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndexes()
    {
        return $this->indexes;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Table.Index indexes = 4;</code>
     * @param array<\Schema\V1\Table\Index>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndexes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\Table\Index::class);
        $this->indexes = $arr;

        return $this;
    }

}

