<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

namespace Schema\V1\Controller;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.Controller.AuthorizationGroup</code>
 */
class AuthorizationGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string table_name = 1;</code>
     */
    protected $table_name = '';
    /**
     * Generated from protobuf field <code>repeated .schema.v1.Controller.AuthorizationCondition authorization_conditions = 2;</code>
     */
    private $authorization_conditions;
    /**
     * Generated from protobuf field <code>bool authentication_model = 3;</code>
     */
    protected $authentication_model = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $table_name
     *     @type array<\Schema\V1\Controller\AuthorizationCondition>|\Google\Protobuf\Internal\RepeatedField $authorization_conditions
     *     @type bool $authentication_model
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Payload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string table_name = 1;</code>
     * @return string
     */
    public function getTableName()
    {
        return $this->table_name;
    }

    /**
     * Generated from protobuf field <code>string table_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Controller.AuthorizationCondition authorization_conditions = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAuthorizationConditions()
    {
        return $this->authorization_conditions;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Controller.AuthorizationCondition authorization_conditions = 2;</code>
     * @param array<\Schema\V1\Controller\AuthorizationCondition>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAuthorizationConditions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\Controller\AuthorizationCondition::class);
        $this->authorization_conditions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool authentication_model = 3;</code>
     * @return bool
     */
    public function getAuthenticationModel()
    {
        return $this->authentication_model;
    }

    /**
     * Generated from protobuf field <code>bool authentication_model = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setAuthenticationModel($var)
    {
        GPBUtil::checkBool($var);
        $this->authentication_model = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AuthorizationGroup::class, \Schema\V1\Controller_AuthorizationGroup::class);

