<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1\Controller;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.Controller.Authorization</code>
 */
class Authorization extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 authorization_id = 1;</code>
     */
    protected $authorization_id = 0;
    /**
     * Generated from protobuf field <code>string table_name = 2;</code>
     */
    protected $table_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $authorization_id
     *     @type string $table_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 authorization_id = 1;</code>
     * @return int
     */
    public function getAuthorizationId()
    {
        return $this->authorization_id;
    }

    /**
     * Generated from protobuf field <code>int32 authorization_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAuthorizationId($var)
    {
        GPBUtil::checkInt32($var);
        $this->authorization_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string table_name = 2;</code>
     * @return string
     */
    public function getTableName()
    {
        return $this->table_name;
    }

    /**
     * Generated from protobuf field <code>string table_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTableName($var)
    {
        GPBUtil::checkString($var, True);
        $this->table_name = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Authorization::class, \Schema\V1\Controller_Authorization::class);

