<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/payloads.proto

namespace Schema\V1\Controller;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>schema.v1.Controller.ResourceCondition</code>
 */
class ResourceCondition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .schema.v1.Controller.ResourceCondition.Operand operands = 1;</code>
     */
    private $operands;
    /**
     * Generated from protobuf field <code>repeated .schema.v1.Operator operators = 2;</code>
     */
    private $operators;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Schema\V1\Controller\ResourceCondition\Operand>|\Google\Protobuf\Internal\RepeatedField $operands
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $operators
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\V1\Payloads::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Controller.ResourceCondition.Operand operands = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOperands()
    {
        return $this->operands;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Controller.ResourceCondition.Operand operands = 1;</code>
     * @param array<\Schema\V1\Controller\ResourceCondition\Operand>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOperands($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Schema\V1\Controller\ResourceCondition\Operand::class);
        $this->operands = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Operator operators = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOperators()
    {
        return $this->operators;
    }

    /**
     * Generated from protobuf field <code>repeated .schema.v1.Operator operators = 2;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOperators($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Schema\V1\Operator::class);
        $this->operators = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResourceCondition::class, \Schema\V1\Controller_ResourceCondition::class);

